### PR TITLE
Update php version for Debian 10

### PR DESCRIPTION
**Pull request by l00ptr**
PHP 7.4 is not packaged for Debian 10. The default version of php on Buster is 7.3

##### SUMMARY
Fix version of PHP

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
role zabbix_web

##### ADDITIONAL INFORMATION
This role doesn't work on Debian Buster the default PHP version is 7.3 and not 7.4

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @l00ptr 

Thank you for making a PR for this. Can you also update the lines:

https://github.com/ansible-collections/community.zabbix/blob/main/molecule/zabbix_web/molecule.yml#L58
https://github.com/ansible-collections/community.zabbix/blob/main/molecule/zabbix_web/molecule.yml#L64

It seems that this breaks the Molecule testing run. (I can not merge a PR with failing jobs)

I am not sure why the Ubuntu 18.04 jobs fails with this, maybe you have an idea?

Kind regards,
Werner

**Comment by l00ptr** [comment]
Don't know why the jobs fails on Ubuntu 18.04, i will have a look

**Comment by l00ptr** [comment]
don't know what's going on with ubuntu, but the probleme is not related to the PHP version

```

  
      def test_zabbix_api(host):
          my_host = host.ansible.get_variables()
          zabbix_url = str(my_host['zabbix_url'])
          hostname = 'http://' + zabbix_url + '/api_jsonrpc.php'
          post_data = '{"jsonrpc": "2.0", "method": "user.login", "params": { "user": "Admin", "password": "zabbix" }, "id": 1, "auth": null}'
          headers = 'Content-Type: application/json-rpc'
          command = "curl -XPOST -H '" + str(headers) + "' -d '" + str(post_data) + "' '" + hostname + "'"
  
          cmd = host.run(command)
  >       assert '"jsonrpc":"2.0","result":"' in cmd.stdout
  E       assert '"jsonrpc":"2.0","result":"' in '{"jsonrpc":"2.0","error":{"code":1,"message":"DB type \\"MYSQL\\" is not supported by current setup.","data":""},"id":1}'
  E        +  where '{"jsonrpc":"2.0","error":{"code":1,"message":"DB type \\"MYSQL\\" is not supported by current setup.","data":""},"id":1}' = CommandResult(command=b'curl -XPOST -H \'Content-Type: application/json-rpc\' -d \'{"jsonrpc": "2.0", "method": "user.... 0 --:--:-- --:--:-- --:--:--     0\r100   236    0   118  100   118   1573   1573 --:--:-- --:--:-- --:--:--  3146\n').stdout
```
I am gonna look deeper a little bit later :)

**Comment by l00ptr** [comment]
@dj-wasabi we are a few people to hit this problem. The CI doesn't work with ubuntu (MySQL related problem).

Please check those PR :
https://github.com/ansible-collections/community.zabbix/pull/320
https://github.com/ansible-collections/community.zabbix/pull/330
https://github.com/ansible-collections/community.zabbix/pull/321

Do you have any clue about this problem ? 


Best regards,
L.

**Comment by dj-wasabi** [comment]
> @dj-wasabi we are a few people to hit this problem. The CI doesn't work with ubuntu (MySQL related problem).
> 
> Please check those PR :
> #320
> #330
> #321
> 
> Do you have any clue about this problem ?
> 
> Best regards,
> L.

Hi @l00ptr 

Yes I have seen it, but I was not able to find a solution for this yet. It seems (Actually 1 link) to be related to the php version of `php-mysql`, but I can not find a way to fix it. So I am open to suggestions for fixing it. 😄

**Comment by dj-wasabi** [comment]
Provided PR #344 to fix CI, so I will merge this PR.

Thanks! 👍

**Pull request merged**
