### PR TITLE
When configuring firewalld, apply new configuration immediately

### PR DESCRIPTION
**Pull request by nathou**
##### SUMMARY

When configuring firewalld, apply new configuration immediately.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

zabbix_agent

##### ADDITIONAL INFORMATION

Without this, you need to manually reload firewalld or add a handler elsewhere.

### CODE REVIEW

**Comment by pyrodie18** [comment]
Thanks for the contribution @nathou .

@D3DeFi  would we consider this a major or minor change?  I personally would say minor but am not set in stone either way.

**Comment by D3DeFi** [comment]
minor, anyone that is using `zabbix_agent_firewall*` should expect that configured changes also get applied. I would even say this is bugfix as it should worked like this from start. But change it in the changelog as minor_changes please.

Otherwise legitimate patch, thank you!

**Review by pyrodie18 — CHANGES_REQUESTED** [review]
Please update the changelog fragment to a minor_change.

**Comment by nathou** [comment]
I just did set the change to "minor".

I fact I realized after creating this pull request (did not have much time to share that, sorry) that there already was a `firewalld-reload` handler, but it only executes when ansible_facts.services exists (has been changed in c011538c92aa31fd425d6c9ca1909c4fe7c14c38)
```
- name: firewalld-reload
  command: "firewall-cmd --reload"
  become: true
  when:
    - ansible_facts.services["firewalld"] is defined
    - ansible_facts.services["firewalld"].state == "running"
```
Those facts are only gathered when [removing zabbix_agent](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/remove.yml), hence the handler is never executed when **installing** zabbix_agent.

Anyway, it seems to me that relying on the firewalld module features is safer.

**Review by D3DeFi — APPROVED** [review]
looks good

@pyrodie18 feel free to merge once CI passes if you are satisfied with the introduced changes since last review

**Review by pyrodie18 — APPROVED** [review]
Great work and thank you....merging

**Pull request merged**
