### PR TITLE
refactor zabbix_group and zabbix_group_info

### PR DESCRIPTION
**Pull request by rockaut**
##### SUMMARY
Refactor zabbix_group to use module_utils.
See #104 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zabbix_group
zabbix_group_info

### CODE REVIEW

**Comment by D3DeFi** [comment]
> LGTM, but merging after #120, then this needs to be rebased

#120 has been merged. Rebase when you have a chance please and than this can be merged :)

Thank you for the contribution @rockaut and good job

**Comment by D3DeFi** [comment]
actually whole `HAS_ZABBIX_API` is no longer needed as well. So try/except block for zabbix_api import can be removed from modules. Same for `missing_required_lib` import

**Comment by rockaut** [comment]
Rebased and @D3DeFi I removed it from zabbix_group_info as it wasn't needed there. But in zabbix_group  there is still a `Already_Exists` exeption from the api so we need it.

I thought about movin the HostGroup Class to module_utils/base.py or an own file/class under modue_utils but I don't know if this would fit. That would be a step further which needs more discussion because it affects the other modules too.

Currently I think it's good.

**Comment by D3DeFi** [comment]
> I thought about movin the HostGroup Class to module_utils/base.py or an own file/class under modue_utils but I don't know if this would fit. That would be a step further which needs more discussion because it affects the other modules too.


I’ve hit the same idea when working on the zabbix_host rework as lots of this stuff is really duplicated across the collection. For example - proxy, groups, host interfaces.

Either to dedicated module_utils files or, if it is even possible and not against some design principles, import from modules itself. Like “from plugins.modules.zabbix_group import ZabbixGroup”

**Pull request merged**
