### PR TITLE
Update mysql.yml

### LINKED ISSUE #804: Error during "Get current value for innodb_default_row_format"
##### SUMMARY

mysql task in the zabbix server role fails to complete with error in conditional check.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_server role
mysql task

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.4]
  config file = /home/derek/.ansible.cfg
  configured module search path = ['/home/derek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/derek/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/derek/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/derek/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/derek/.ansible.cfg) = ['/home/derek/.ansible/inventories/hosts.yml']
DEFAULT_ROLES_PATH(/home/derek/.ansible.cfg) = ['/home/derek/.ansible/roles']
HOST_KEY_CHECKING(/home/derek/.ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu 20.04.5
mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
Zabbix 6.0.8
community.zabbix 1.8.0

##### STEPS TO REPRODUCE

```yaml
Issue was observed while running the mysql.yml task in zabbix_server role.
```

##### EXPECTED RESULTS

previously completed successful as I was able to install the zabbix server

##### ACTUAL RESULTS

```paste below
fatal: [zabbix-server.lan -> {{ delegated_dbhost }}]: FAILED! => {"msg": "The conditional check 'install_mysql_version.msg is version('5.6', '>=')' failed. The error was: Version comparison failed: '<' not supported between instances of 'str' and 'int'\n\nThe error appears to be in '/home/derek/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_server/tasks/mysql.yml': line 99, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"MySQL | Get current value for innodb_default_row_format\"\n  ^ here\n"}

offending task below.

- name: "MySQL | Get current value for innodb_default_row_format"
  community.mysql.mysql_variables:
    variable: innodb_default_row_format
    login_host: "{{ zabbix_server_mysql_login_host | default(omit) }}"
    login_user: "{{ zabbix_server_mysql_login_user | default(omit) }}"
    login_password: "{{ zabbix_server_mysql_login_password | default(omit) }}"
    login_port: "{{ zabbix_server_mysql_login_port | default(omit) }}"
    login_unix_socket: "{{ zabbix_server_mysql_login_unix_socket | default(omit) }}"
  delegate_to: "{{ delegated_dbhost }}"
  register: mysql_innodb_default_row_format
  when:
    - install_mysql_version.msg is version('5.6', '>=')
  tags:
    - zabbix-server
    - database
```

### PR DESCRIPTION
**Pull request by derekpurdy**
##### SUMMARY

Fixes #804 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

zabbix_server role
mysql task

##### ADDITIONAL INFORMATION

```paste below
documented in https://github.com/ansible-collections/community.zabbix/issues/804
```

### CODE REVIEW

**Review by BGmot — COMMENTED** [review]
Won't we fail with "undefined variable" here https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_server/tasks/mysql.yml#L130 ?

**Comment by derekpurdy** [comment]
It proceded to run the rest of the role when I made this change in my test environment. But I'll leave it up to you to confirm.

**Comment by BGmot** [comment]
I don't know why bunch of tests got cancelled, waiting for somebody who knows GitHub workflows better to take a look.

**Review by D3DeFi — APPROVED** [review]

**Comment by D3DeFi** [comment]
I have honestly no idea why the checks were cancelled.., but I've triggered their re-run.

Otherwise LGTM and can merge after tests pass.

**Pull request merged**
