### PR TITLE
Create zabbix_globalmacro.py

### PR DESCRIPTION
**Pull request by ttestscripting**
Created Global Macros Plugin 

##### SUMMARY
Created the Global Macro Plugin. 

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
Zabbix Module to create and update global macros. 

##### ADDITIONAL INFORMATION
New module based on the hostmacro module to create and update global macros. Secret Macros will always be updated since there is no way to validate the current value.  ( Documentation may need to be updated for global macros.)

### CODE REVIEW

**Comment by ttestscripting** [comment]
Not sure how to resolve the checks that are failing. Any help/advice on resolving the issues would be greatly appreciated, Both pulls I have submitted appear to be failing at the same point.

**Comment by dj-wasabi** [comment]
@sky-joker  / @D3DeFi 
Any idea what is going on right now?

**Comment by sky-joker** [comment]
Thanks, @ttestscripting for the contribution!  
If you don't mind, could you please change your branch name from main to any name?

For example

**before**

ttestscripting:main

**after**

ttestscripting:add_new_module_zabbix_globalmacro

I'll review the module after changing your branch name :-)

**Comment by D3DeFi** [comment]
@dj-wasabi @ttestscripting I am diving into failing 5.0 tests (timeouts) to see what can be done

**Comment by dj-wasabi** [comment]
> @dj-wasabi @ttestscripting I am diving into failing 5.0 tests (timeouts) to see what can be done

Thanks bro! 💋

**Review by D3DeFi — CHANGES_REQUESTED** [review]
Very nice :rocket: :heart: 

Same as for your zabbix_inventory contribution. Can you please:
- add changelog fragment
- mention in README.md
- add `version_added: 1.4.0`
- add integrations tests? You can mostly copy `tests/integration/targets/test_zabbix_hostmacro`

**Comment by D3DeFi** [comment]
CI fixed in #374 (at least I hope so)

One reason why submitting from `main` is not a good idea is that we cannot do `git fetch ID/pull/branch` to test out the changes locally. However, this is not fix/feature patch so it is rather easy to just grab whole file and paste somewhere.

**Comment by sky-joker** [comment]
Thanks, @D3DeFi for following up!

**Pull request closed without merging**
