### PR TITLE
Installing Zabbix 5.2 for the roles

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Installing Zabbix 5.2 for the roles

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Created ticket on Zabbix https://support.zabbix.com/projects/ZBX/issues/ZBX-18565 and updated https://support.zabbix.com/projects/ZBX/issues/ZBX-18561

**Comment by dsteinkopf** [comment]
Any progress here? Thank you very much.

**Comment by sky-joker** [comment]
@dj-wasabi
In some test result, there are the errors occurs that isn't found SQL schema file.  
Do you know the cause of the error?

**Comment by dj-wasabi** [comment]
> @dj-wasabi
> In some test result, there are the errors occurs that isn't found SQL schema file.
> Do you know the cause of the error?

Yes, see: https://support.zabbix.com/projects/ZBX/issues/ZBX-18565?filter=allopenissues

**Comment by sky-joker** [comment]
@dj-wasabi 


Thank you for telling me that information!  
Now seem the following error occurs on CI.

**zabbix_proxy**

```
fatal: [zabbix-web-pgsql-centos7]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'zabbix-server-pgsql' found available, installed or updated", "rc": 126, "results": ["No package matching 'zabbix-server-pgsql' found available, installed or updated"]}
```

**zabbix_javagateway**

```
fatal: [zabbix-javagateway-debian]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '52'\n\nThe error appears to be in '/home/runner/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_javagateway/tasks/Debian.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}
```

**Review by D3DeFi — APPROVED** [review]
Looks good! Great work

**Pull request merged**
