### PR TITLE
Possibility to add custom includes in apache vhost config (zabbix_web)

### PR DESCRIPTION
**Pull request by johansenha**
##### SUMMARY
This features requests opens the possiblity to add custom rules should as headers to the apache_vhosts config such as:

```
Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains;"
```

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- role: zabbix_web

##### ADDITIONAL INFORMATION

**playbook**

```
- hosts: zabbix
  roles:
   - role: geerlingguy.apache
      apache_mods_enabled:
        - headers
  - role: zabbix_web
      zabbix_apache_custom_includes:
        - Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains;"
```

### CODE REVIEW

**Review by BGmot — COMMENTED** [review]
Please update documentation https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_WEB_ROLE.md

**Comment by johansenha** [comment]
> Please update documentation https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_WEB_ROLE.md

File has already been updated https://github.com/ansible-collections/community.zabbix/pull/935/files#diff-2f124eaa49dcaa1737ed67dd1efda370111fa034edbe8b81f84bcda9f34671e1. Are you missing anything?

**Comment by BGmot** [comment]
Thanks @johansenha I am approving, somebody will merge.

**Review by BGmot — APPROVED** [review]

**Comment by D3DeFi** [comment]
Thank you for this contribution! :)

**Pull request merged**
