### PR TITLE
Boolean when is wrong

### PR DESCRIPTION
**Pull request by lingfish**
##### SUMMARY
I think this is meant to not be "not".

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
community.zabbix

### CODE REVIEW

**Comment by dj-wasabi** [comment]
@lingfish 

To be honest, I don't know? (Not a Windows User so I don't know what that 'dot' does/means...)

**Comment by lingfish** [comment]
Hi, it was #376 by @ironbishop that added it.  Best that I can tell, they were trying to only run that task if `zabbix_agent_win_include` ended up being a string that looked like it had a dot in it, as in `zabbix_agentd.d`, following the standard of "dot d" include dirs.

**Comment by ironbishop** [comment]
True, i didn't account for the '.d' folder. But this check is meant to skip the folder creation when you want to include a single file, not to a folder. Maybe something like `'.conf' not in zabbix_agent_win_include` would be better?

**Comment by dj-wasabi** [comment]
So how do we continue? Shall I merge it, or will @lingfish update the PR with comment from @ironbishop ?

**Comment by ironbishop** [comment]
i can't commit to his branch, but I can create my own if he's unable to go on with the change

**Comment by dj-wasabi** [comment]
> i can't commit to his branch, but I can create my own if he's unable to go on with the change

Ok! 👍 
Will merge the PR. Thanks @lingfish and @ironbishop

**Pull request merged**
