### PR TITLE
1.3.0prep

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
1.3.0 mainly because of the #345

### CODE REVIEW

**Comment by dj-wasabi** [comment]
No 2.0.0?

**Comment by D3DeFi** [comment]
Nah, actually #345 requires 1.2.1, but I honestly don't know how to release it with just a security patch.

Only think I can think of is to checkout new branch from 1.2.0 latest commit a cherry-pick the security fixes to it, but then we would be stack with the branch forever.

Also not possible to release 1.2.1 if there are som many features prepared to be released in roles since 1.2.0 so I settled for the middle ground.

I still don't know what would 2.0.0 bring us except possibility to drop zabbix 3.x for modules.

**Comment by dj-wasabi** [comment]
I always thought that with Ansible 3.0, we had to deliver a version 2.0.0. But maybe I am/was wrong about this.

**Comment by D3DeFi** [comment]
> I always thought that with Ansible 3.0, we had to deliver a version 2.0.0. But maybe I am/was wrong about this.

Major versions of collections work only in one way. They are considered breaking releases and will not be included by default in current ansible version. There is no requirement to have major version ready for each new release of ansible.

Ansible 3.0.z is out already. That means if we release 2.0.0 of this collection it will not be included in any ansible 3.y.z release, only minor and bugfix releases for the major version that is in the ansible 3.0.x will be included with minor releases of ansible (that means any 1.y.z).

E.g. we do 2.0.0 now then it will get to ansible 4.0.0. We do 1.3.0 now it will get to both ansible 3.1.0 and 4.0.0 if we dont create collection 2.0.0 before release of 4.0.0.

**Comment by D3DeFi** [comment]
Im am going ahead then and merge this since we are long overdue with security fixes release I guess

**Pull request merged**
