### PR TITLE
SQL scripts for Zabbix 6.0+ moved to /usr/share

### LINKED ISSUE #810: TASK [community.zabbix.zabbix_server : Get the file for create.sql >= 3.0] failed with ubuntu 22.04 and zabbix 6.2.3
##### SUMMARY

Playbook fails with an error:
```
TASK [community.zabbix.zabbix_server : Get the file for create.sql >= 3.0] ****************************************************************************************************************************************
fatal: [zabbix]: FAILED! => {"changed": false, "cmd": "ls -1 /usr/share/doc/zabbix-sql-scripts/mysql/server.sq*", "delta": "0:00:00.007845", "end": "2022-09-24 09:44:02.960897", "msg": "non-zero return code", "rc": 2, "start": "2022-09-24 09:44:02.953052", "stderr": "ls: cannot access '/usr/share/doc/zabbix-sql-scripts/mysql/server.sq*': No such file or directory", "stderr_lines": ["ls: cannot access '/usr/share/doc/zabbix-sql-scripts/mysql/server.sq*': No such file or directory"], "stdout": "", "stdout_lines": []}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_server

##### ANSIBLE VERSION

```ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION

```vagrant@ansible:~$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible
 2.12. Current version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]. This feature will be 
removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

```

##### OS / ENVIRONMENT / Zabbix Version

```
vagrant@zabbix:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```
```
vagrant@zabbix:~$ dpkg -l | grep zabbix
ii  zabbix-server-mysql                   1:6.2.3-1+ubuntu22.04                   amd64        Zabbix network monitoring solution - server (MySQL)
ii  zabbix-sql-scripts                    1:6.2.3-1+ubuntu22.04                   all          Zabbix network monitoring solution - sql-scripts
```

##### STEPS TO REPRODUCE

Run installation of zabbix server using ansible role on server with clean ubuntu 22.04

```yaml
  - hosts: zabbix
    become: yes
    roles:
      - role: community.zabbix.zabbix_server
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
        zabbix_server_dbport: 3306
        zabbix_server_dbpassword: super-secure-password
```

##### EXPECTED RESULTS

Zabbix server installed

##### ACTUAL RESULTS

Zabbix server not installed

```
TASK [community.zabbix.zabbix_server : Get the file for create.sql >= 3.0] ****************************************************************************************************************************************
fatal: [zabbix]: FAILED! => {"changed": false, "cmd": "ls -1 /usr/share/doc/zabbix-sql-scripts/mysql/server.sq*", "delta": "0:00:00.007845", "end": "2022-09-24 09:44:02.960897", "msg": "non-zero return code", "rc": 2, "start": "2022-09-24 09:44:02.953052", "stderr": "ls: cannot access '/usr/share/doc/zabbix-sql-scripts/mysql/server.sq*': No such file or directory", "stderr_lines": ["ls: cannot access '/usr/share/doc/zabbix-sql-scripts/mysql/server.sq*': No such file or directory"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ***************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************
zabbix                     : ok=56   changed=17   unreachable=0    failed=1    skipped=29   rescued=0    ignored=0   
```

### PR DESCRIPTION
**Pull request by mcbrineellis**
##### SUMMARY

Fixes #810

In Zabbix [6.0.9](https://www.zabbix.com/documentation/6.0/en/manual/introduction/whatsnew609) and [6.2.3](https://www.zabbix.com/documentation/current/en/manual/introduction/whatsnew623) SQL scripts have been moved from the `/usr/share/doc` directory to `/usr/share` in Zabbix packages.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Updated the `datafiles_path` fact for the `zabbix_proxy` and `zabbix_server` roles.

##### ADDITIONAL INFORMATION

Before change:
```
TASK [Install Zabbix Server] ****************************************************************************************************
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 
2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [community.zabbix.zabbix_server : Include OS-specific variables] ***********************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Determine Latest Supported Zabbix Version] ***********************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Install the correct repository] **********************************************************
included: /Users/connor/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_server/tasks/Debian.yml for 172.21.12.109

TASK [community.zabbix.zabbix_server : Include Zabbix gpg ids] ******************************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Set some variables] **********************************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Set some variables] **********************************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Set some facts] *****************************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Set some facts for Zabbix >= 3.0 && < 5.4] **************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Set some facts for Zabbix >= 5.4] ***********************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Installing gnupg] ***************************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Install gpg key] ****************************************************************
changed: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Installing repository Ubuntu] ***************************************************
changed: [172.21.12.109] => (item=deb-src)
changed: [172.21.12.109] => (item=deb)

TASK [community.zabbix.zabbix_server : Debian | Create /etc/apt/preferences.d/] *************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Configuring the weight for APT] *************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : apt-get clean] ***************************************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Check for the dpkg exclude line] *********************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Allow Zabbix dpkg installs to /usr/share/doc/zabbix*] ************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Installing zabbix-server-pgsql] *************************************************
changed: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Installing zabbix-sql-scripts] **************************************************
changed: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Install Ansible module dependencies] ********************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Install Mysql Client package] ***************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian 10 | Install Mysql Client package] ************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Debian | Install PostgreSQL Client package] **********************************************
changed: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Installing the postgresql database] ******************************************************
included: /Users/connor/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_server/tasks/postgresql.yml for 172.21.12.109

TASK [community.zabbix.zabbix_server : Set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)] ***
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : Set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)] ***
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Delegated | Create database] ************************************************
ok: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Delegated | Create database user] *******************************************
changed: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Delegated | Create timescaledb extension] ***********************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Remote | Create database] ***************************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Remote | Create database user] **********************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Remote | Create timescaledb extension] **************************************
skipping: [172.21.12.109]

TASK [community.zabbix.zabbix_server : PostgreSQL | Create schema] **************************************************************
fatal: [172.21.12.109]: FAILED! => {"changed": true, "cmd": "set -euxo pipefail\nFILE=server.sql\ncd /usr/share/doc/zabbix-sql-scripts/postgresql\nif [ -f ${FILE}.gz ]\n  then zcat ${FILE}.gz > /tmp/create.sql\nelse\n  cp ${FILE} /tmp/create.sql\nfi\ncat /tmp/create.sql | psql -h 'localhost' -U 'zabbix-server' -d 'zabbix' -p '5432'\ntouch /etc/zabbix/schema.done\nrm -f /tmp/create.sql\n", "delta": "0:00:00.003323", "end": "2022-10-04 04:33:12.698211", "msg": "non-zero return code", "rc": 1, "start": "2022-10-04 04:33:12.694888", "stderr": "+ FILE=server.sql\n+ cd /usr/share/doc/zabbix-sql-scripts/postgresql\n/bin/bash: line 2: cd: /usr/share/doc/zabbix-sql-scripts/postgresql: No such file or directory", "stderr_lines": ["+ FILE=server.sql", "+ cd /usr/share/doc/zabbix-sql-scripts/postgresql", "/bin/bash: line 2: cd: /usr/share/doc/zabbix-sql-scripts/postgresql: No such file or directory"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [geerlingguy.postgresql : restart postgresql] *******************************************************************

PLAY RECAP **********************************************************************************************************************
172.21.12.109              : ok=46   changed=15   unreachable=0    failed=1    skipped=26   rescued=0    ignored=0 
```

After change:
```
TASK [Install Zabbix Server] ********************************************************************
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This 
feature will be removed in version 2.16. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

TASK [zabbix_server : Include OS-specific variables] ********************************************
ok: [172.21.12.109]

TASK [zabbix_server : Determine Latest Supported Zabbix Version] ********************************
skipping: [172.21.12.109]

TASK [zabbix_server : Install the correct repository] *******************************************
included: /Users/connor/dev/test-role/roles/zabbix_server/tasks/Debian.yml for 172.21.12.109

TASK [zabbix_server : Include Zabbix gpg ids] ***************************************************
ok: [172.21.12.109]

TASK [zabbix_server : Set some variables] *******************************************************
ok: [172.21.12.109]

TASK [zabbix_server : Set some variables] *******************************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Set some facts] **************************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Set some facts for Zabbix >= 3.0 && < 5.4] ***********************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Set some facts for Zabbix = 5.4] *********************************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Set some facts for Zabbix >= 6.0] ********************************
ok: [172.21.12.109]

TASK [zabbix_server : Debian | Installing gnupg] ************************************************
ok: [172.21.12.109]

TASK [zabbix_server : Debian | Install gpg key] *************************************************
ok: [172.21.12.109]

TASK [zabbix_server : Debian | Installing repository Ubuntu] ************************************
ok: [172.21.12.109] => (item=deb-src)
ok: [172.21.12.109] => (item=deb)

TASK [zabbix_server : Debian | Create /etc/apt/preferences.d/] **********************************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Configuring the weight for APT] **********************************
skipping: [172.21.12.109]

TASK [zabbix_server : apt-get clean] ************************************************************
ok: [172.21.12.109]

TASK [zabbix_server : Check for the dpkg exclude line] ******************************************
ok: [172.21.12.109]

TASK [zabbix_server : Allow Zabbix dpkg installs to /usr/share/doc/zabbix*] *********************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Installing zabbix-server-pgsql] **********************************
ok: [172.21.12.109]

TASK [zabbix_server : Debian | Installing zabbix-sql-scripts] ***********************************
ok: [172.21.12.109]

TASK [zabbix_server : Debian | Install Ansible module dependencies] *****************************
ok: [172.21.12.109]

TASK [zabbix_server : Debian | Install Mysql Client package] ************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian 10 | Install Mysql Client package] *********************************
skipping: [172.21.12.109]

TASK [zabbix_server : Debian | Install PostgreSQL Client package] *******************************
ok: [172.21.12.109]

TASK [zabbix_server : Installing the postgresql database] ***************************************
included: /Users/connor/dev/test-role/roles/zabbix_server/tasks/postgresql.yml for 172.21.12.109

TASK [zabbix_server : Set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)] ***
ok: [172.21.12.109]

TASK [zabbix_server : Set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)] ***
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Delegated | Create database] *********************************
ok: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Delegated | Create database user] ****************************
ok: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Delegated | Create timescaledb extension] ********************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Remote | Create database] ************************************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Remote | Create database user] *******************************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Remote | Create timescaledb extension] ***********************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Create schema] ***********************************************
changed: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Create TimescaleDB hypertables] ******************************
skipping: [172.21.12.109]

TASK [zabbix_server : Get complete path] ********************************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Check if we have a create dir] ********************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Set fact] *****************************************************************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Importing schema file] ***************************************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Importing images file] ***************************************
skipping: [172.21.12.109]

TASK [zabbix_server : PostgreSQL | Importing data file] *****************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Configure zabbix-server] **************************************************
changed: [172.21.12.109]

TASK [zabbix_server : Create include dir zabbix-server] *****************************************
changed: [172.21.12.109]

TASK [zabbix_server : Configure zabbix-server alertscripts] *************************************
skipping: [172.21.12.109]

TASK [zabbix_server : Configure zabbix-server externalscripts] **********************************
skipping: [172.21.12.109]

TASK [zabbix_server : Zabbix-server started] ****************************************************
changed: [172.21.12.109]
```

### CODE REVIEW

**Comment by mcbrineellis** [comment]
Will add test results and changelog shortly.

**Comment by mcbrineellis** [comment]
Should be good to go I believe, please review!  Thanks!

**Review by D3DeFi — APPROVED** [review]
LGTM, good job! :)

**Comment by mcbrineellis** [comment]
Thanks @D3DeFi ! The tests it's failing are on the verify stage and don't seem to have a clear error to me. Please let me know if there is anything I can do to help here.

Connor

**Comment by D3DeFi** [comment]
It seems that zabbix-server doesn't start with thes changes. Although I am not that familiar with tests related to roles, @mu1f407  @pyrodie18 are you able to confirm that is indeed the case here?

**Comment by pyrodie18** [comment]
It's not because of the move of the files (although that was a problem).  It's the default value we have for one of the Caches in the config file.  Don't have my laptop in front of me to see which one it was off hand.

**Comment by mcbrineellis** [comment]
Is this something I can help solve?

**Comment by pyrodie18** [comment]
> Is this something I can help solve?

Check the defaults for the config file against the actual defaults for the software

**Comment by mcbrineellis** [comment]
Let's see if that suggestion helps.  Thanks for the guidance!
@pyrodie18 or @D3DeFi can you please approve the workflow?

**Review by D3DeFi — APPROVED** [review]
Thanks! :)

**Pull request merged**
