### PR TITLE
Update local 'ansible_python_interpreter' to make sure to install the…

### LINKED ISSUE #602: bug: Install local python-netaddr package fails even if requirement is satisfied
##### SUMMARY
Install local python-netaddr package task fails even if the netaddr requirement is already met. 

I am running as a non-sudo user so the task is unable to install netaddr itself. However, I have installed netaddr on teh controller and as shown below pip can see the requirement is met, but the task still fails. Please could the task be updated to allow it to pass if the requirement is met. Even if it cant install netaddr itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-agent

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dgibbs/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dgibbs/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Run the ansible-agent role as a non sudo user

```yaml

```

##### EXPECTED RESULTS

For the task to pass if netaddr is already installed on the controller

##### ACTUAL RESULTS

```
TASK [community.zabbix.zabbix_agent : Install local python-netaddr package] ****
task path: /home/www/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:49
Using module file /usr/lib/python3/dist-packages/ansible/modules/pip.py
Pipelining is enabled.
 ESTABLISH LOCAL CONNECTION FOR USER: user
 EXEC /bin/sh -c 'HOME=/root /usr/bin/python3 && sleep 0'
FAILED - RETRYING: [forest-tools.hlswfixes.com -> localhost]: Install local python-netaddr package (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "cmd": [
        "/usr/bin/python3",
        "-m",
        "pip.__main__",
        "install",
        "netaddr"
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "netaddr"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "retries": 4
}

MSG:

stdout: Requirement already satisfied: netaddr in /usr/local/lib/python3.9/dist-packages (0.8.0)

:stderr: WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/root/.local'
Check the permissions.
```

```paste below

```

### PR DESCRIPTION
**Pull request by dj-wasabi**
Update local 'ansible_python_interpreter' to make sure to install the packages correctly.

##### SUMMARY

Fixes #602 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

zabbix_agent

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by dgibbs64** [comment]
I will test today. Thank you 👍🏻

**Comment by chimmmpie** [comment]
This branch worked for me. (debian 10)
```
ansible 2.9.27
python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```
netaddr 0.8.0 was correctly installed using none root user

**Review by D3DeFi — APPROVED** [review]
This looks good to me. Can we merge this @dj-wasabi ?

**Review by pyrodie18 — APPROVED** [review]

**Comment by pyrodie18** [comment]
@D3DeFi  see any reason not to go ahead and merge this?

**Comment by D3DeFi** [comment]
> @D3DeFi see any reason not to go ahead and merge this?

Waited for another pair of :eyes: . Yeah I think this is good :)

**Pull request merged**
