### PR TITLE
1.9.2prep

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
1.9.2 release

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
looks good to me! Merge at your leisure 🚀

**Comment by BGmot** [comment]
Thank you.

**Comment by BGmot** [comment]
@D3DeFi, sorry, forgot to commit all CHANGELOG changes, please review one more time.

**Comment by D3DeFi** [comment]
hmm, I actually didnt notice it at first, but now when I think about it, it is quite a batch of minor changes and only 1 bugfix. Everything seems fine as a bugfix release, but the new modules may be confusing

not sure if 1.9.2 or 1.10.0 in this case :/ I would ideally opt for 1.9.2 without new modules, but that may be cumbersome. What do you think?

**Comment by BGmot** [comment]
I totally screwed CHANGELOG, this
```
- zabbix_agent and zabbix_proxy roles - fixed a bug whith ansible_python_interpreter not being set correctly in some corner cases
```
should have gone into bug fixes and my major concern. Can we somehow release 1.9.2 with only two bug fixes?

**Comment by D3DeFi** [comment]
> I totally screwed CHANGELOG, this
> 
> ```
> - zabbix_agent and zabbix_proxy roles - fixed a bug whith ansible_python_interpreter not being set correctly in some corner cases
> ```
> 
> should have gone into bug fixes and my major concern. Can we somehow release 1.9.2 with only two bug fixes?

to be honest I am not sure how, but galaxy publish relies on tag existence in this repo. Perhaps if we fork 1.9.1 tag to 1.9.2 branch and cherry-pick only changes you want to release from main to that branch? Then tag that branch with 1.9.2

Up to try it out?

**Comment by BGmot** [comment]
> Up to try it out?

Yes. Let me try, sounds like it is doable this way.

**Comment by BGmot** [comment]
@D3DeFi I've created new branch 1.9.2prep can you take a look please?

**Comment by BGmot** [comment]
I thought we needed to tag this branch without merging into main, no?

**Pull request closed without merging**
