### PR TITLE
BGmot 

### LINKED ISSUE #939: All role tests are failing
Since Apr 3rd, 2023 all our role tests are failing https://github.com/ansible-collections/community.zabbix/actions. Does anybody know what is going on???

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
Github runner image switched to Ubuntu 20.
zabbix_action module: renaming `message` parameter into `op_message`.
Fixes #939

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_action

### CODE REVIEW

**Review by pyrodie18 — APPROVED** [review]

**Review by D3DeFi — APPROVED** [review]
I like the changes a lot! It is a great job, but this will prevent us from releasing anything else than 2.0 with breaking changes. Are we ready yet?

What about roles? I am having hard time to keep up with all the changes lately and as you know I am not pushing any of my own :/

**Comment by BGmot** [comment]
> I like the changes a lot! It is a great job, but this will prevent us from releasing anything else than 2.0 with breaking changes. Are we ready yet?
> 
> What about roles? I am having hard time to keep up with all the changes lately and as you know I am not pushing any of my own :/

If we don't release 2.0 as the next release we'll never release it (I thought we'd release it after 1.9.0). We have a discussion about 2.0 here https://github.com/ansible-collections/community.zabbix/issues/774 need to somehow to sum up what's left and I am going to devote some of my time to tackle the release. So are we good to merg this?

**Comment by pyrodie18** [comment]
From my perspective, the only thing left for 2.0 is the agent role which I can probably get done this weekend and documentation updates.  I haven't brought in the 6.4 update, although looking at the changes, it shouldn't be hard to port that in.  Do we want me to go ahead and bring this PR into 2.0 so that we can finish the testing?

**Comment by D3DeFi** [comment]
Ok, we can merge then. If you guys have time to push for 2.0 then let's do! :)

**Comment by pyrodie18** [comment]
OK, 2.0.0-dev2 has been rebased and I pulled in @BGmot changes to the testing.  I think I may have broken the runners with all of the changes and crap but going to give it a few minutes and see if it clears itself out.

**Comment by pyrodie18** [comment]
Ok, looks like we're good and things are moving but getting a bunch of new errors with sanity and plugin-integration.  Going to close this PR.  Once the current run of my merge request into 2.0.0-dev2 is done running, I'm going to force merge it (even though its failing) so we'll have a common place to work from.  Can continue to troubleshoot and make changes in #774

**Pull request merged**
