### PR TITLE
Fix deprecation warnings: second attempt

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
Additional fixes for #857 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
All modules

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
deprecation changes look good 👍 , but it seems you also accidentally pushed 1.9.1 preparation also to this branch?

**Comment by BGmot** [comment]
You merged 1.9.1prep into main and I as usual rebased before submitting PR -(
What should I do now? delete the branch and create new one off the old main?

**Comment by BGmot** [comment]
> You merged 1.9.1prep into main and I as usual rebased before submitting PR -( What should I do now? delete the branch and create new one off the old main?

Actually no... I need to digest what happened.

**Comment by D3DeFi** [comment]
> You merged 1.9.1prep into main and I as usual rebased before submitting PR -( What should I do now? delete the branch and create new one off the old main?
this should help
```
git checkout main
git pull
git checkout <your branch>
git rebase main
git push -f origin <your branch>
```

**Pull request closed without merging**
