### PR TITLE
Prepare agent, server and proxy for Zabbix 6.0

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Prepare configuration and installation for Zabbix 6.0.

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```
This will be in preparation for #560

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
I like the changes, seems they will work properly (and they are not that invasive so why wouldn't they? ) :)

**Comment by dj-wasabi** [comment]
> I like the changes, seems they will work properly (and they are not that invasive so why wouldn't they? ) :)

I did not had any issues with the zabbix_web, which was the most painful one with the previous ones with the php upgrades.. 😄

**Comment by dj-wasabi** [comment]
@ragingpastry Do you have any suggestions/improvements for this PR, or should we just merge it? Thank you!

**Comment by ragingpastry** [comment]
Looks good to me!

**Review by ragingpastry — APPROVED** [review]

**Pull request merged**
