### PR TITLE
1.9.2prep

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
1.9.2 release.

### CODE REVIEW

**Review by D3DeFi — COMMENTED** [review]
looks ok, why close it though? Something forgotten?

**Comment by BGmot** [comment]
I thought we needed to tag this branch without merging into main, no?

**Comment by D3DeFi** [comment]
oh, that is true

**Comment by BGmot** [comment]
I re-opened so all the checked have a chance to pass, then close it and tag without merging?

**Comment by BGmot** [comment]
Closing without merging as this is "only bug-fix" release.

**Comment by BGmot** [comment]
I am sorry @D3DeFi but I kept thinking about this weird 1.9.2 release and we need to merge the 1.9.2prep branch because it will only update these files and it's is actually needed for the next release be "on top" of 1.9.2:
```
Merge made by the 'recursive' strategy.
 CHANGELOG.rst                 | 10 ++++++++++
 README.md                     |  2 +-
 changelogs/.plugin-cache.yaml |  2 +-
 changelogs/changelog.yaml     | 14 ++++++++++++++
 galaxy.yml                    |  2 +-
 5 files changed, 27 insertions(+), 3 deletions(-)
```
Though we must not delete 1.9.2prep branch as we usually do after release (the 1.9.2 tag is there).
So I am re-openting this PR.

**Comment by D3DeFi** [comment]
Or we can maybe merge it back into main somehow, but I am not sure if that would work. I don't mind having this branch present at all and don't be sorry, these are uncharted waters anyway for our repo! :)

**Comment by BGmot** [comment]
> Or we can maybe merge it back into main somehow

Just click "Squash and merge" -)
I merged locally - nothing disastrous happened, only changlog, readme and galaxy.yml got updated with 1.9.2. Anyway main should have this info.

**Comment by D3DeFi** [comment]
All good! :) Thank you

**Pull request merged**
