### PR TITLE
Update zabbix.py

### PR DESCRIPTION
**Pull request by rdmarsh**
Python3 and DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by D3DeFi — CHANGES_REQUESTED** [review]
Hi, thanks for submitting the patch. However, as Ansible states in [this document](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/shebang.html), shebang must stay in the previous form.

Change for the configparser is ok

**Comment by D3DeFi** [comment]
@rdmarsh can you please revert changes to shebang and only include SafeConfigParser so we can merge this one? :)

**Comment by rdmarsh** [comment]
> @rdmarsh can you please revert changes to shebang and only include SafeConfigParser so we can merge this one? :)

Not great with GitHub, did that work?

**Review by D3DeFi — APPROVED** [review]
Yes, this is fine, thank you! :)

**Pull request merged**
