### PR TITLE
Zabbix WEB (Ubuntu and RedHat) and run in CI

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Add Molecule tests for Zabbix Web for RedHat and Ubuntu. I still have some issues with Debian which I don't get to work. Having CI for Zabbix Web is important, so Debian can follow.

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
Yay, more tests! Good job @dj-wasabi 

Quickly went through changes, looks good on a first look, check are passing and thus I believe you managed to get it right.

LGTM

**Comment by dj-wasabi** [comment]
I forgot to update the documentation as I have added some new properties for the role. Don't merge yet, will update this PR first.

**Comment by dj-wasabi** [comment]
> I forgot to update the documentation as I have added some new properties for the role. Don't merge yet, will update this PR first.

Done

**Review by sky-joker — APPROVED** [review]
LGTM

Thank you @dj-wasabi :)

**Pull request merged**
