### PR TITLE
1.9.0prep

### LINKED ISSUE #832: Release 1.9.0
It has been some time since 1.8.0 release and we should ship 1.9.0.

Any of you guys @BGmot @mu1f407 @pyrodie18 interested in trying that by yourself or should I go ahead and release?

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
New colellction version PR.

Fixes #832 

##### ISSUE TYPE
- New collection version Pull Request

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
Looks good to me. Let's wait a couple more days for #787 resolution

**Comment by BGmot** [comment]
Thanks for reviewing and guiding through this!

**Comment by johansenha** [comment]
@D3DeFi  since https://github.com/ansible-collections/community.zabbix/pull/787 is merged can we apply the change to release 1.9.0?

**Comment by D3DeFi** [comment]
> @D3DeFi since #787 is merged can we apply the change to release 1.9.0?

yep :) sole reason we waited with this PR is that issue :)

@BGmot can you please rebase this PR a top of latest `main` changes and re-run `antsibull-changleg` with updated date? I will try to merge it on the same day you update and then you can push tag to release on galaxy

**Comment by BGmot** [comment]
Can we squeeze in one more https://github.com/ansible-collections/community.zabbix/issues/526 ?

**Comment by D3DeFi** [comment]
> Can we squeeze in one more https://github.com/ansible-collections/community.zabbix/issues/526 ?

Sure, there is zero rush to release :)

**Review by D3DeFi — APPROVED** [review]
Looks good 👍

**Comment by BGmot** [comment]
Hope I did everything right. 
Not sure about Galaxy steps - where do we disable/enable automatic publish? I still see 1.8.0 in Galaxy.
> Additional manual steps are required when automatic publish to Ansible Galaxy is not enabled in the repository.

**Comment by BGmot** [comment]
Oh, nevermind, I see  1.9 in Galaxy now. So fingeres crossed now and let's embrace for bug reports flow.

**Comment by D3DeFi** [comment]
Thanks for publishing! :)

**Comment by BGmot** [comment]
> Thanks for publishing! :)

Thanks for guidance -)

**Pull request merged**
