### PR TITLE
1.2.0prep

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Prep for 1.2.0 release
and then we can make minimal 2.0.0 release with dropping 3.x support on plugins

I would also like to get as much open PRs (we have right now in the repo) in as possible

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
CHANGELOG

### CODE REVIEW

**Comment by dj-wasabi** [comment]
I just merged https://github.com/ansible-collections/community.zabbix/pull/304, can we include this one as well? 😄

**Comment by D3DeFi** [comment]
> I just merged https://github.com/ansible-collections/community.zabbix/pull/304, can we include this one as well? 😄 

Ofc, I will be rebasing this in a following days anyway so it will include all merges

**Comment by dj-wasabi** [comment]
LGTM.. 👍

**Comment by sky-joker** [comment]
Thank you @D3DeFi for released v1.2.0!

**Pull request merged**
