### PR TITLE
Molecule 6

### PR DESCRIPTION
**Pull request by eb4x**
##### SUMMARY

Upgrading the molecule testing to version 6.

Future molecule wants to eliminate the various drivers, and just have ansible (delegated driver) set up the infrastructure. This PR does that. Creates all networks/containers in `create.yml` and destroys them in `destroy.yml`.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

molecule, ci

##### ADDITIONAL INFORMATION
A small smattering of other improvements, and just removing stuff that does not need to be there.

### CODE REVIEW

**Comment by eb4x** [comment]
I think the failing tests are flukes, maybe just re-run the failed ones to verify.

**Comment by pyrodie18** [comment]
> I think the failing tests are flukes, maybe just re-run the failed ones to verify.

Ya pretty sure they are....rerunning now

**Comment by pyrodie18** [comment]
Is there a reason not to just move straight to the current version of 24.6.0?  https://github.com/ansible/molecule/discussions/4136

**Comment by eb4x** [comment]
> Is there a reason not to just move straight to the current version of 24.6.0? [ansible/molecule#4136](https://github.com/ansible/molecule/discussions/4136)

Not really sure, I wasn't aware of the newer releases. It has Python 3.10 as minimum requirement, but I see we bumped testing to 3.11. I'll add a commit to bump to the latest.

**Comment by eb4x** [comment]
Maybe just re-run the failed tests again.

**Review by pyrodie18 — APPROVED** [review]

**Pull request merged**
