### PR TITLE
add an own bug_report template

### PR DESCRIPTION
**Pull request by rockaut**
##### SUMMARY
It's basically the same from https://github.com/ansible-collections/.github/tree/master/.github/ISSUE_TEMPLATE but with "Zabbix Version" added.

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by D3DeFi** [comment]
@gundalow is it ok if we adjust issue template? Maybe some more in the future to suite more our needs

**Comment by gundalow** [comment]
Yup, you can adjust this however you want.

For example, add a question about what Zabbix version is installed, any relevant zabbix configuration, etc.

As long as the file name & title matches whats in https://github.com/ansible-collections/.github/tree/master/.github/ISSUE_TEMPLATE the files in the community.zabbix repo will be used instead of the generic version

**Comment by D3DeFi** [comment]
That means we need to have other templates present in the directory as well, right?

**Comment by gundalow** [comment]
Nop, you can just override the ones you want to

**Pull request merged**
