### PR TITLE
Refactor TimescaleDB setup/configuration

### PR DESCRIPTION
**Pull request by eb4x**
##### SUMMARY
Just refactor of the timescaledb setup to make configuration more consistent/reliable.

##### ISSUE TYPE

- Refactor Pull Request

##### COMPONENT NAME
zabbix_server

### CODE REVIEW

**Comment by eb4x** [comment]
I think I got ahead of myself with moving the timescaledb extension task. Will move it back unless the extension can be enabled by less privileged users. In either case, it needs a small modification.

**Comment by pyrodie18** [comment]
Is this ready @eb4x

**Comment by eb4x** [comment]
> Is this ready @eb4x

Nope, sorry about the hold-up. I've converted it to a draft.

**Comment by eb4x** [comment]
> Management of PostgreSQL extension failed: permission denied to create  extension "timescaledb"
> HINT:  Must have CREATE privilege on current database to create this extension.

So I guess that answers that, I'll revert the create-extension move.

**Review by pyrodie18 — APPROVED** [review]

**Pull request merged**
