### PR TITLE
Copy ignore-2.12.txt to ignore-2.13.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-926794724

### CODE REVIEW

**Comment by Andersson007** [comment]
```
ERROR: Package 'ansible-core' requires a different Python: 2.7.18 not in '>=3.8'
Error: Process completed with exit code 1.
```

**Comment by Andersson007** [comment]
dear maintainers, please relaunch tests here after fixing Python related things, see updates starting with https://github.com/ansible-collections/overview/issues/45#issuecomment-924298319

**Comment by D3DeFi** [comment]
> 
> 
> dear maintainers, please relaunch tests here after fixing Python related things, see updates starting with [ansible-collections/overview#45 (comment)](https://github.com/ansible-collections/overview/issues/45#issuecomment-924298319)

Sure, I will try to look at it asap the next day. Thank you for opening this

**Comment by D3DeFi** [comment]
sorry for asking, I don't know how to do this yet, but is there some easy way for me to rebase this or only you can do this?

CI should be fixed now in main branch

**Comment by Andersson007** [comment]
@D3DeFi i don't know, I'll rebase it, no problem:)

**Comment by Andersson007** [comment]
@D3DeFi green now, thanks for fixing the CI!

**Pull request merged**
