### PR TITLE
Devel roles migration

### LINKED ISSUE #24: Document roles in main README.md and galaxy.yml files
##### SUMMARY
Update repo's main README.md and galaxy.yml files to include new roles and information about them.

Do this before merging `devel-roles-migration` to master branch.

Dependent on the completion of:
- #20
- #21 
- #22 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
README.md
galaxy.yml

### LINKED ISSUE #52: Regarding CHANGELOG
##### SUMMARY
Its apparent that at some point we will be releasing next version of this collection. In the meantime, changes are accumulating. 

Should we require that with each change to a module or roles, an entry will be added to the CHANGELOG.md under "`devel`" section or something like that?

##### ISSUE TYPE
- Documentation Report

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Merge changes approved in `devel-roles-migration` to `master`. PR for CHANGELOG entries will follow.

This precedes tagging of `0.2.0` and releasing collection with roles on Galaxy! hoorayy! :)

Fixes #24 
Fixes #52

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Nice! 👍

**Comment by dj-wasabi** [comment]
Maybe we should merge https://github.com/ansible-collections/community.zabbix/pull/81 and then merge to master, so the documentation is also up2date. In the mean time I can work on the molecule/CI part and on Zabbix 5.0.

**Comment by D3DeFi** [comment]
> Maybe we should merge #81 and then merge to master, so the documentation is also up2date. In the mean time I can work on the molecule/CI part and on Zabbix 5.0 for the roles.

Yes, definitely! :) We will be waiting for automatic galaxy publishing tool that will come next week. So we have still some time :)

**Comment by D3DeFi** [comment]
@sky-joker @dj-wasabi does this format for changelog makes sense to you?
https://github.com/D3DeFi/community.zabbix/blob/changelog-entries/CHANGELOG.md

Very... very much inspired from Ansible repository

**Comment by dj-wasabi** [comment]
@D3DeFi 

Yes, it makes more sense than what I did, just pasting the titles of the PR's. It also provides a nice overview of it is a bugfix or something new. 👍

**Comment by D3DeFi** [comment]
Looks good to me. @sky-joker can I proceed with merging this to the `master` branch?

**Comment by sky-joker** [comment]
> @sky-joker @dj-wasabi does this format for changelog makes sense to you?
> https://github.com/D3DeFi/community.zabbix/blob/changelog-entries/CHANGELOG.md
> 
> Very... very much inspired from Ansible repository

That's great!
Let's merge to `master` :)

**Pull request merged**
