### PR TITLE
Renamed integration roles to prevent ansible-test confusing them with…

### PR DESCRIPTION
**Pull request by D3DeFi**
… roles from roles/ directory

##### SUMMARY
Since we decided to rename roles to `zabbix_`, `ansible-test` seems to prefer `roles/*` over `test/integration/targets/*`.

Not even sure if this is intended feature, but I've opened a bug report in ansible/ansible#69981

To fix this on our side, I've decided to go with KISS principle and simply rename our integration test roles rather than look for more hacking solution like this:

`tests/integration/targets/zabbix_host -> tests/integration/targets/test_zabbix_host`

Follow up to #72

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/integration/targets/*

### CODE REVIEW

**Comment by D3DeFi** [comment]
@sky-joker can you take a look please? Does this make sense to you?

**Comment by D3DeFi** [comment]
I will open a PR from `devel-roles-migration` to `master` once we merge this simple rename. I wouldn't be waiting for a fix in ansible as that can take some time and this migration already took us long enough.

I would like to tag `0.2.0` during the weekend and ask for galaxy release. Do you think it is achievable @sky-joker ?

**Comment by sky-joker** [comment]
I wonder do I need to ask @gundalow to make a config that automatically pushes to the galaxy when I add a tag?

https://github.com/ansible-collections/community.zabbix/issues/15#issuecomment-619150845

**Comment by D3DeFi** [comment]
Thanks for looking at this!

> I wonder do I need to ask @gundalow to make a config that automatically pushes to the galaxy when we add a tag?

We probably still need to

**Comment by gundalow** [comment]
Yup, I'm a bit behind on that :(
If you are happy to wait a but before pushing a gut tag, we can test here next week?

**Comment by D3DeFi** [comment]
I believe we can @gundalow :) At least I will have more time to format CHANGELOG entries :)

**Comment by sky-joker** [comment]
> If you are happy to wait a but before pushing a gut tag, we can test here next week?

@gundalow, please test next week :)

**Pull request merged**
