### PR TITLE
Added initial version of the upgrade document

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Added initial version of the upgrade document

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by D3DeFi** [comment]
I like this very much. Do you think some information in **bold** on top of that document regarding name changes in roles is required? Is there a chance that user will miss such change (- -> _)?

I am thinking if anything like this is necessary for plugins. I bet ansible will clearly state how to use collection in porting guide and nothing else notable comes to my mind.

@sky-joker @rockaut any ideas on your side before merging?

**Comment by rockaut** [comment]
Merge it ... I think it modules may benefit of this too, yes.

**Comment by dj-wasabi** [comment]
> I like this very much. Do you think some information in **bold** on top of that document regarding name changes in roles is required? Is there a chance that user will miss such change (- -> _)?


Ah yes, good one! I will update the PR tonight! 👍

**Comment by dj-wasabi** [comment]
@D3DeFi I updated the document and described a bit about the renaming. Please let me know if this is fine or needs more improvements.

**Pull request merged**
