### PR TITLE
updated CHANGELOG.md to reflect changes made in the collection

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Changelog before 0.2.0 release

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
CHANGELOG.md

### CODE REVIEW

**Comment by D3DeFi** [comment]
@dj-wasabi @sky-joker do we want to do these steps before releasing?:

- prepare some migration documentation for user (e.g. to rename roles, use FQCNs, and so on)
- prepare some explicit documentation about which ansible roles and python modules are required for each role/module - our current doc seems to be a little bit vague on this one?

Or do it after release?

I also think that we have some time until Ansible 2.10 will be released as users would probably not be migrating to collections until then. At least not in a masses.

**Comment by dj-wasabi** [comment]
I would say, lets release the 0.2.0 with what we have now. In the mean time we can get some experience and fixing some issues that people have now before the masses are using the collection and have issues. My 2 cents.

**Comment by D3DeFi** [comment]
my bad requesting review on already approved changes in #80

**Comment by D3DeFi** [comment]
> I would say, lets release the 0.2.0 with what we have now. In the mean time we can get some experience and fixing some issues that people have now before the masses are using the collection and have issues. My 2 cents.

I agree, I am going to push git tag now

**Pull request merged**
