### PR TITLE
Add zabbix_maintenance integration test

### PR DESCRIPTION
**Pull request by sky-joker**
##### SUMMARY
This PR adds zabbix_maintenance module integration test.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zabbix_maintenance

### CODE REVIEW

**Comment by D3DeFi** [comment]
I wonder why this works. Module seems to set `start_time` of the maintenance to something like`time.now()` every time it is run.

**Comment by sky-joker** [comment]
Thank you @D3DeFi for merging.  
Sorry, I late in checking your comment.  

I noticed that when I tried to update only the desc parameter, it didn't update.  
The cause of this is under investigation.

> Module seems to set start_time of the maintenance to something liketime.now() every time it is run.

It would be nice to add `start_time` and `end_time` parameters to this module, what do you think?

**Comment by D3DeFi** [comment]
> It would be nice to add `start_time` and `end_time` parameters to this module, what do you think?

Can you please expand the idea a bit further? I am not sure if I fully understand how it would work. 

Do we, for example, require users to depend on the ansible fact `ansible_date_time.time`? But in that case `start_time` would always change as well when rerunning the playbook multiple times.

Only use case that came to my mind is that if you for example wanted to schedule maintenance each day for a specific hour, then this would make sense. On the other hand, you can still schedule recurring maintenance once and be done with it. Maybe users are handling something like this already by running playbook at the specific hour via cron/Ansible Tower/etc..

I presume that most popular use case right now is to put server to a maintenance, do some grunt work like OS upgrade and then remove the maintenance. Judging by the design of the module, I believe that it was written with this intention as well. But there is downside that it is not idempotent right now :(

**Comment by sky-joker** [comment]
Thank you for your opinion.  

> I presume that most popular use case right now is to put server to a maintenance, do some grunt work like OS upgrade and then remove the maintenance.

I see, Is it like this? (write to playbook to the following processing like)

* register for the maintenance
* something process execute(update and so on)
* unregister for the maintenance

For example, I thought it would be useful to be able to specify the following parameters in the module as well.

```yaml
- zabbix_zabbix_maintenance:
    (snip)
    start_time: yyyy/mm/dd HH:MM:ss
    end_time: yyyy/mm/dd HH:MM:ss
    (snip)
```

This is in anticipation of registering for maintenance in advance.  
There may not be much demand for it, but...

**Comment by D3DeFi** [comment]
> There may not be much demand for it, but...

Well, I ain't against it :) Would you be interested in proposing a feature PR for this? If so, it would be welcome. I am sure it would find its uses eventually. But just to be sure, let's leave default behavior as it is right now.

**Comment by sky-joker** [comment]
Thank you :)
I'll think about this feature a bit more.

**Pull request merged**
