### PR TITLE
Fix name of config file Zabbix Agent2

### PR DESCRIPTION
**Pull request by david-sieg**
##### SUMMARY
Fixes [#1265](https://github.com/ansible-collections/community.zabbix/issues/1265)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Set correct value for Zabbix Agent 2 config file.

### CODE REVIEW

**Comment by pyrodie18** [comment]
Thanks for the PR....please add a change fragment.

**Comment by david-sieg** [comment]
https://github.com/ansible-collections/community.zabbix/compare/main...david-sieg:community.zabbix:fix_zabbix2_win_config_name

**Comment by pyrodie18** [comment]
Please see https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

**Comment by david-sieg** [comment]
> Please see https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

done

**Comment by pyrodie18** [comment]
Thanks for the addition

**Pull request merged**
