### PR TITLE
Run CI against the correct branch

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
This is likely my fault, though we've been running CI against a branch that hasn't been updated in a long time.

I expect a load of things to fail with this change, though we can push further changes to this branch till all is green.

**2.10**
- [x] ERROR: plugins/modules/zabbix_action.py:994:103: E225: missing whitespace around operator
- [x] ERROR: plugins/modules/zabbix_group_info.py:98:8: ansible-deprecated-no-collection-name: No collection name found in call to Display.deprecated or AnsibleModule.deprecate
- [X] ERROR: plugins/modules/zabbix_host_info.py:193:8: ansible-deprecated-no-collection-name: No collection name found in call to Display.deprecated or AnsibleModule.deprecate
- [X] ERROR: plugins/modules/zabbix_template.py:730:8: ansible-deprecated-no-collection-name: No collection name found in call to Display.deprecated or AnsibleModule.deprecate
- [X] ERROR: plugins/modules/zabbix_proxy.py:0:0: deprecation-collection-missing: AnsibleModule.argument_spec.interface.options.main: If removed_in_version or removed_at_date is specified, removed_from_collection must be specified as well for dictionary value @ data['argument_spec']['interface']['options']['main']. Got {'type': 'int', 'default': 0, 'removed_in_version': '2.14'}
- [X] ERROR: plugins/modules/zabbix_proxy.py:0:0: deprecation-collection-missing: AnsibleModule.argument_spec.interface.options.type: If removed_in_version or removed_at_date is specified, removed_from_collection must be specified as well for dictionary value @ data['argument_spec']['interface']['options']['type']. Got {'type': 'int', 'default': 0, 'removed_in_version': '2.14'}
- [X] ERROR: plugins/modules/zabbix_proxy.py:0:0: invalid-deprecated-version: Argument 'main' in argument_spec found in interface has an invalid removed_in_version number '2.14': invalid semantic version '2.14'
- [X] ERROR: plugins/modules/zabbix_proxy.py:0:0: invalid-deprecated-version: Argument 'type' in argument_spec found in interface has an invalid removed_in_version number '2.14': invalid semantic version '2.14'

**2.11**
- [X] Copy 2.10 ignore list

**General**
- [x] junit_xml missing. Check we have `--requirements` specified
- [x] For integration tests, which OS?
- [X] sanity tests Ansible-base 2.10
- [X] sanity tests Ansible-base devel (2.11)
- [X] integration tests Ansible-base 2.10
- [ ] integration tests Ansible-base devel (2.11)
- [ ] Sanity: which Python versions
- [ ] integration: which Python versions
- [x] Code coverage https://codecov.io/gh/ansible-collections/community.zabbix

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by gundalow** [comment]
I can fix the sanity tests, though I don't understand why the integration tests are failing
https://github.com/ansible-collections/community.zabbix/runs/799160622#step:7:2391

**Comment by D3DeFi** [comment]
> I can fix the sanity tests, though I don't understand why the integration tests are failing
> https://github.com/ansible-collections/community.zabbix/runs/799160622#step:7:2391

Actual failure is happening here:
https://github.com/ansible-collections/community.zabbix/runs/799160622#step:7:1925

step:7:2391 is cause of `--retry-on-error`

@gundalow is it possible that ansible is somehow modifying our return data via `exit_json`? We are using default `zabbix` password and that means `zabbix_export` gets translated to `******_export` on stdout, but if ansible 2.10 or something has started to modify json object as well, we may have a problem.

In plain integration role `test_zabbix_template`:
```yaml
- assert:
    that:
      - gather_template_result.template_json.zabbix_export.groups.0.name == 'Linux servers'
      - gather_template_result.template_json.zabbix_export.groups.1.name == 'Templates'
```

Seems that @sky-joker hit this same problem in #99 for `test_zabbix_template_info`:
```yaml
- name: "test - Set key to template_export_key variable(This deals with the key being masked)"
  set_fact:
    template_export_key: "{{ item }}"
  loop: "{{ fetch_template_json_format_result.template_json.keys() | list }}"
  when:
    - item | regex_search('_export')

- assert:
    that:
      - fetch_template_json_format_result.template_json[template_export_key].date is defined
      - fetch_template_json_format_result.template_json[template_export_key].groups.0.name == "Templates"
      - fetch_template_json_format_result.template_json[template_export_key].templates.0.name == "ExampleTemplateForTempleteInfoModule"
      - fetch_template_json_format_result.template_json[template_export_key].templates.0.template == "ExampleTemplateForTempleteInfoModule"
```

**Comment by D3DeFi** [comment]
It is kinda ugly, but I can push that workaround to this branch for `test_zabbix_template`

**Comment by gundalow** [comment]
> @gundalow is it possible that ansible is somehow modifying our return data via `exit_json`? We are using default `zabbix` password and that means `zabbix_export` gets translated to `******_export` on stdout, but if ansible 2.10 or something has started to modify json object as well, we may have a problem.


Ah good spot. Ansible is doing the "correct thing". Though as  Ansible can't tell if `zabbix` refers to the password or another string, it's REDACTING it all. We've seen this before when network engineers use the default password of `admin`.

Would it be possible to change the password before ansible-test starts running the integration tests? Is that *just* a case of updating https://github.com/ansible-collections/community.zabbix/blob/master/docker-compose.yml and the passwords in the integration tests?

**Comment by D3DeFi** [comment]
> Would it be possible to change the password before ansible-test starts running the integration tests? Is that _just_ a case of updating https://github.com/ansible-collections/community.zabbix/blob/master/docker-compose.yml and the passwords in the integration tests?

Actually no, those are passwords for DB and other stuff. Seems that [Zabbix containers](https://hub.docker.com/r/zabbix/zabbix-server-pgsql) don't come with ENV variable that would allow this and we would need to find some other way that would prolly require SQL INSERT.

**Comment by gundalow** [comment]
@D3DeFi Ah, OK. thanks for looking into this I guess we will stick with https://github.com/ansible-collections/community.zabbix/pull/105/commits/ed8af605f288dd3a4ebe23e641f2c74b980f61c3 for the moment then, unless you want to do an SQL INSERT? I don't mind either way.

**Comment by D3DeFi** [comment]
> @D3DeFi Ah, OK. thanks for looking into this I guess we will stick with [ed8af60](https://github.com/ansible-collections/community.zabbix/commit/ed8af605f288dd3a4ebe23e641f2c74b980f61c3) for the moment then, unless you want to do an SQL INSERT? I don't mind either way.

commit is already done so lets use that for now

**Comment by pabelanger** [comment]
recheck

**Comment by D3DeFi** [comment]
rebased on top of a master since there were colliding changes merged 

so, sanity done, integrations done, 2.11 done, now we move to the tasks present under General?

**Comment by gundalow** [comment]
@D3DeFi 
1) Good point about Operating System, you are right that this doesn't testing against Ubuntu/CentOS/etc doesn't increase test coverage as we are testing against multiple versions of Zabbix instead

2) Yup to disabling the test

3) I've added codecov support, this may need tweaking, though I think maybe this needs to be merged to work.

I don't have any more time to work on this PR, so if people are happy can we merge as is, I hope it's an improvement over what we have today.

If anyone wants to take a look at the remaining `general` items that could be done in a follow-up PR.

**Comment by gundalow** [comment]
Might have spotted what's wrong with coverage, testing...

**Comment by D3DeFi** [comment]
@gundalow I can take it from here, but can you please point me to the right resource about codecov (or is it [ansible testing units](https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html))? Do we need to start writting unit tests? We have none so far.

Aand supported python versions - matching upstream?
```Currently Ansible can be run from any machine with Python 2 (version 2.7) or Python 3 (versions 3.5 and higher) installed.```

**Comment by gundalow** [comment]
@D3DeFi Ansible can generate codecoverage from unit tests or integration tests. This seems to be working now.
Best case would be to use the full matrix of Python versions, though I'm also OK with you picking a Py2 and Py3 for integration tests.

**Comment by gundalow** [comment]
https://codecov.io/gh/ansible-collections/community.zabbix/pull/105/tree?path=plugins%2Fmodules

**Comment by gundalow** [comment]
@D3DeFi This PR is all yours if you'd like to extend it further.

Only thing left is to consider if you want integration tests against `devel` as well as `stable-2.10`, as well as which Python versions

**Comment by gundalow** [comment]
@D3DeFi actually, can we merge this as it. I've received some there good feedback on how to structure the GitHub action, which I'd like to test out here in a follow up PR. I've found when writing docs having real examples (like community.zabbix) helps.

So I'd like to propose, if you are happy:
1. Merge this PR, so everyone can benefit from testing against the correct thing
2. I'll raise a follow-up PR

**Comment by D3DeFi** [comment]
> @D3DeFi actually, can we merge this as it. I've received some there good feedback on how to structure the GitHub action, which I'd like to test out here in a follow up PR. I've found when writing docs having real examples (like community.zabbix) helps.
> 
> So I'd like to propose, if you are happy:
> 
>     1. Merge this PR, so everyone can benefit from testing against the correct thing
> 
>     2. I'll raise a follow-up PR

Yeah ok, I will think about supporting additional python versions later

**Comment by D3DeFi** [comment]
Thank you @gundalow :)

**Comment by gundalow** [comment]
Thanks.

**Pull request merged**
