### PR TITLE
Refactor zabbix web

### PR DESCRIPTION
**Pull request by eb4x**
##### SUMMARY
This is a refactor of the zabbix_web role.

##### ISSUE TYPE
- Refactor Pull Request

##### COMPONENT NAME
zabbix_web role

##### ADDITIONAL INFORMATION
Some small fixes to zabbix_server role, zabbix_web uses a more recent version of mysql, which uncovered some issues with pymysql.

### CODE REVIEW

**Comment by eb4x** [comment]
I'm posting this as a draft, I haven't figured it all out yet. There are some things that don't really line up between the os_families. Like why are php packages installed for debian, but redhat packages goes unused.

**Comment by eb4x** [comment]
I'm taking this out of draft. I think the changes here are good cleanups. Not really done yet, but if merged, I'll create a new PR with the rest of the changes for this refactor. (otherwise I'll push to this when ready.)

**Comment by pyrodie18** [comment]
You good for me to pull this in @eb4x

**Comment by eb4x** [comment]
Yep just merge if you feel like. I can create a second PR once I figure out how to strip the last bits in `tasks/RedHat.yml`. I think these are all good parts of the refactor.

**Review by pyrodie18 — APPROVED** [review]
OK tracking that Proxy is currently failing but pretty sure it has nothing to do with this, and I'm already working on it.  So going to pull this in so that #1194 can rebase and come in.

**Pull request merged**
