### PR TITLE
User directory module and compatibility with 6.2

### LINKED ISSUE #754: Compatibility with Zabbix 6.2
##### SUMMARY
All modules need to be compatible with recently released Zabbix 6.2

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Two modules fail integration tests against Zabbix 6.2:
- zabbix_authentication
- zabbix_host_info

##### ANSIBLE VERSION
```
ansible 2.10.17
  config file = None
  configured module search path = ['/home/ey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ey/env_py39_ans210/lib/python3.9/site-packages/ansible
  executable location = /home/ey/env_py39_ans210/bin/ansible
  python version = 3.9.5 (default, Nov 23 2021, 15:27:38) [GCC 9.3.0]
```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix 6.2.

##### STEPS TO REPRODUCE
```
ansible-test integration -v --color --diff --python 3.9 --requirements
```

##### EXPECTED RESULTS
All tests should pass.

##### ACTUAL RESULTS
For zabbix_authentication module getting following error:
```
TASK [test_zabbix_authentication : test - update all authentication setting] ***************************************************************************************************************************************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Failed to update authentication setting, Exception: ('Error -32602: Invalid params., Invalid parameter \"/\": unexpected parameter \"ldap_host\". while sending {\"jsonrpc\": \"2.0\", \"method\": \"authentication.update\", \"params\": {\"authentication_type\": \"0\", \"http_auth_enabled\": \"1\", \"http_login_form\": \"0\", \"http_strip_domains\": \"comp,any\", \"http_case_sensitive\": \"1\", \"ldap_configured\": \"1\", \"ldap_host\": \"ldap://localhost\", \"ldap_port\": \"389\", \"ldap_base_dn\": \"ou=Users,ou=system\", \"ldap_search_attribute\": \"uid\", \"ldap_bind_dn\": \"uid=ldap_search,ou=system\", \"ldap_case_sensitive\": \"1\", \"ldap_bind_********\": \"********\", \"saml_auth_enabled\": \"1\", \"saml_sso_url\": \"https://localhost/SAML2/SSO\", \"saml_slo_url\": \"https://localhost/SAML2/SLO\", \"saml_username_attribute\": \"uid\", \"saml_sp_entityid\": \"https://localhost\", \"saml_nameid_format\": \"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\", \"saml_sign_messages\": \"1\", \"saml_sign_assertions\": \"1\", \"saml_sign_authn_requests\": \"1\", \"saml_sign_logout_requests\": \"1\", \"saml_sign_logout_responses\": \"1\", \"saml_encrypt_nameid\": \"1\", \"saml_encrypt_assertions\": \"1\", \"saml_case_sensitive\": \"1\", \"passwd_min_length\": \"70\", \"passwd_check_rules\": \"15\"}, \"auth\": \"80efc2870ecbc31a9e2b80374cc0a5f3\", \"id\": 3}', -32602)"}

```

For zabbix_host_info module getting following error:
```
TASK [test_zabbix_host_info : test - Prepare host for zabbix_host_info module] *************************************************************************************************************************************
[WARNING]: The value "1" (type int) was converted to "'1'" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
[WARNING]: The value "10050" (type int) was converted to "'10050'" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
ok: [testhost] => {"changed": false}

TASK [test_zabbix_host_info : assert] ******************************************************************************************************************************************************************************
fatal: [testhost]: FAILED! => {
    "assertion": "prepare_host_result.changed is sameas true",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
Fixes #754 #755

##### ISSUE TYPE
- New Module (and Feature) Pull Request

##### COMPONENT NAME
zabbix_authentication
zabbix_user_directory

##### ADDITIONAL INFORMATION
zabbix_user_directory module is brand new, come in to accommodate new feature of Zabbix 6.2 "Multiple sources for LDAP authentication
zabbix_authentication module updated to work with Zabbix 6.2

### CODE REVIEW

**Review by mu1f407 — APPROVED** [review]
Very nice addition! Thank you for your work @BGmot! Approved.

**Review by D3DeFi — APPROVED** [review]
Very nice addition, thank you! :)

**Comment by damsy** [comment]
Hi, the new version seems  not to be showing up on ansible galaxy..

**Comment by BGmot** [comment]
> Hi, the new version seems not to be showing up on ansible galaxy..

It won't until we release new version of this collection.

**Pull request merged**
