### PR TITLE
Delete vars/zabbix.yml

### PR DESCRIPTION
**Pull request by masa-orca**
##### SUMMARY

- Deliting no used vars/zabbix.yml

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- roles/*
##### ADDITIONAL INFORMATION

- `vars/zabbix.yml` is never used in now.
- This commit is related to https://github.com/ansible-collections/community.zabbix/issues/1002

```paste below

```

### CODE REVIEW

**Review by pyrodie18 — CHANGES_REQUESTED** [review]
Please toss in a change fragment but great work!

**Comment by masa-orca** [comment]
I have added changelog.

**Review by pyrodie18 — APPROVED** [review]

**Comment by pyrodie18** [comment]
@BGmot got a sec to take a look?

**Review by BGmot — APPROVED** [review]
Looks ok to me, feel free to merge if all tests successful

**Pull request merged**
