### PR TITLE
Convert bool values to lowercase in modules documentation.x

### LINKED ISSUE #911: Consider using true/false for all booleans in docs
Based on the [community decision](https://github.com/ansible-community/community-topics/discussions/120) to use `true/false` for boolean values in documentation and examples, we ask that you evaluate booleans in this collection and consider changing any that do not use `true/false` (lowercase).

See [documentation block format](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#documentation-block) for more info (specifically, option defaults).

If you have already implemented this or decide not to, feel free to close this issue.

---

P.S. This is auto-generated issue, please raise any concerns [here](https://github.com/ansible-community/community-team/issues/60)

### PR DESCRIPTION
**Pull request by BGmot**
##### SUMMARY
Fixes #911 

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by BGmot** [comment]
I don't know why third-party-check fails thus don't know how to fix it.
Please review and if there is no concerns I'll merge, purely cosmetic changes.

**Comment by dj-wasabi** [comment]
> I don't know why third-party-check fails thus don't know how to fix it. Please review and if there is no concerns I'll merge, purely cosmetic changes.

Maybe isue at galaxy side?
```
2023-03-29 18:44:19.978794 \| TASK [deploy-artifacts : Install require-project collection using ansible-galaxy]
2023-03-29 19:10:53.814041 \| PRE-RUN END RESULT_TIMED_OUT: [untrusted : github.com/ansible/ansible-zuul-jobs/playbooks/ansible-galaxy-importer/pre.yaml@master]
```
Or did it fail in previous runs as well?

**Review by dj-wasabi — APPROVED** [review]

**Comment by BGmot** [comment]
> Or did it fail in previous runs as well?

no, it's sporadic. From time to time we get these failures. Do you know what system is performing this check and what is actually checked?

**Comment by BGmot** [comment]
Thanks for approving!

**Comment by dj-wasabi** [comment]
> > Or did it fail in previous runs as well?
> 
> no, it's sporadic. From time to time we get these failures. Do you know what system is performing this check and what is actually checked?

I really have no idea.. This was (and probably) is something from Ansible itself, that each collection should follow. So that is something I just accept that it is there.. :)

**Pull request merged**
