### PR TITLE
tags support for zabbix_maintenance

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
This PR extends #356 as it has now become stale and there is no communication.

As a bonus, it does not work (flagged WIP till Jira issue below gets some love) :(
https://support.zabbix.com/browse/ZBX-20146

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/modules/zabbix_maintenance.py

### CODE REVIEW

**Comment by D3DeFi** [comment]
duplicates #356

**Comment by D3DeFi** [comment]
TIL tags work only for maintenance with data collection

**Comment by D3DeFi** [comment]
This PR is good to be merged now, only waiting for #522 first to not introduce additional rebasing shenanigans. I will rebase this PR if needed

**Comment by tuxmartin** [comment]
Hi, do you have any news about this issue? It will be very useful.

**Comment by D3DeFi** [comment]
Oh I completely forgot about this PR :(

**Comment by D3DeFi** [comment]
@ragingpastry would you be willing to give this a quick look if it is ok to be merged?

**Review by ragingpastry — APPROVED** [review]

**Comment by tuxmartin** [comment]
@D3DeFi Thank you for merge. When will the next version be released?

**Comment by D3DeFi** [comment]
lets see from #614

we will try to decide there

**Comment by tuxmartin** [comment]
@D3DeFi Hi, do you have any news about next release?

#614 is already closed.

**Comment by D3DeFi** [comment]
tbh I dont, I am sorry. Communication regarding that was deferred to [gitter chat](https://gitter.im/community-zabbix/community?at=61e96e005dc6213cd4efe349). I will re-ignite the discussion

**Pull request merged**
