### PR TITLE
Re-add defaults, documentation entry for the var zabbix_apache_custom_includes

### LINKED ISSUE #985: Zabbix Web fails on "Install apache vhost" when zabbix_apache_custom_includes is undefined
##### SUMMARY
It appears that the feature added in #935 is causing an error when `zabbix_apache_custom_includes` is left undefined.
My playbooks started failing with this bug since the latest release.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

#935 

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.9]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.3 (main, Apr 18 2023, 19:33:01) [GCC 12.2.1 20220924]
  jinja version = 3.1.2
  libyaml = False
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT / Zabbix Version

- Ubuntu 20.04
- Zabbix 6.0
- Running Ansible in Docker.

##### STEPS TO REPRODUCE

```yaml
- name: Install Zabbix Web Frontend
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_web
    apply:
      become: true
  vars:
    zabbix_server_name: "{{ inventory_hostname }}"
    zabbix_web_version: 6.0
    zabbix_api_server_url: "{{ inventory_hostname }}"
    zabbix_server_version: 6.0
    zabbix_server_database: pgsql
    zabbix_server_database_long: postgresql
    zabbix_server_dbport: 5432
    zabbix_server_dbname: zabbix
    zabbix_server_dbuser: zabbix
    zabbix_server_dbpassword: "{{ zabbix6_zabbix_server_dbpassword }}"
    zabbix_timezone: "{{ zabbix6_zabbix_timezone }}"
    zabbix_web_memory_limit: "{{ zabbix6_zabbix_web_memory_limit }}"
    zabbix_web_post_max_size: "{{ zabbix6_zabbix_web_post_max_size }}"
    zabbix_web_upload_max_filesize: "{{ zabbix6_zabbix_web_upload_max_filesize }}"
```

##### EXPECTED RESULTS

The task should run fine, even without passing any value for the newly added variable `zabbix_apache_custom_includes`.

##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_web : Apache | Install apache vhost] *************
task path: /root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_web/tasks/apache.yml:63
<10.10.10.1> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.10.10.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/ssh/id_ed25519"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/34b2d43aa5"' 10.10.10.1 '/bin/sh -c '"'"'echo ~ansible && sleep 0'"'"''
<10.10.10.1> (0, b'/home/ansible\n', b"OpenSSH_9.3p1, OpenSSL 3.1.0 14 Mar 2023\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 10.10.10.1 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<10.10.10.1> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.10.10.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/ssh/id_ed25519"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/34b2d43aa5"' 10.10.10.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir "` echo /home/ansible/.ansible/tmp/ansible-tmp-1683758001.5181444-1354-168828736745944 `" && echo ansible-tmp-1683758001.5181444-1354-168828736745944="` echo /home/ansible/.ansible/tmp/ansible-tmp-1683758001.5181444-1354-168828736745944 `" ) && sleep 0'"'"''
<10.10.10.1> (0, b'ansible-tmp-1683758001.5181444-1354-168828736745944=/home/ansible/.ansible/tmp/ansible-tmp-1683758001.5181444-1354-168828736745944\n', b"OpenSSH_9.3p1, OpenSSL 3.1.0 14 Mar 2023\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 10.10.10.1 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<10.10.10.1> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.10.10.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/ssh/id_ed25519"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/34b2d43aa5"' 10.10.10.1 '/bin/sh -c '"'"'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1683758001.5181444-1354-168828736745944/ > /dev/null 2>&1 && sleep 0'"'"''
<10.10.10.1> (0, b'', b"OpenSSH_9.3p1, OpenSSL 3.1.0 14 Mar 2023\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 10.10.10.1 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 1128, in do_template
    res = self.environment.concat(rf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 88, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 88, in <listcomp>
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 89, in root
  File "/usr/lib/python3.11/site-packages/jinja2/tests.py", line 195, in test_iterable
    iter(value)
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'zabbix_apache_custom_includes' is undefined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/plugins/action/template.py", line 138, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 1162, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'zabbix_apache_custom_includes' is undefined
fatal: [zabbix.myhostname.net]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'zabbix_apache_custom_includes' is undefined"
}
```

### PR DESCRIPTION
**Pull request by mcbrineellis**
##### SUMMARY

The variable appears to have been accidentally removed in the final 2.0.0 tag release.
I've readded it to what I believe to be the appropriate locations.

Fixes #985

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`TASK [community.zabbix.zabbix_web : Apache | Install apache vhost]`

### CODE REVIEW

**Review by pyrodie18 — CHANGES_REQUESTED** [review]
@mcbrineellis , What does that variable tie back to?  I don't see it used anywhere in 2.0.0 and looking back, I can't see it in the last 1.X release either.

**Comment by mcbrineellis** [comment]
@pyrodie18 it was added in #935 and it's still present in the 2.0.0 release `roles/zabbix_web/templates/apache_vhost.conf.j2` but was removed elsewhere.

So the issue I opened is because without the default of [], it errors that the var is undefined.

**Comment by pyrodie18** [comment]
Ya I just realized I had a filter in place when I did a search so it wasn't checking the .j2 files.  I'm slightly surprised it didn't error our in our testing though because it should have.

**Review by pyrodie18 — APPROVED** [review]

**Comment by BGmot** [comment]
@mcbrineellis please make following changes, after that molecule tests should go through.
```
diff --git a/molecule/requirements.txt b/molecule/requirements.txt
index bec205a..7b0bc88 100644
--- a/molecule/requirements.txt
+++ b/molecule/requirements.txt
@@ -1,11 +1,13 @@
 # Install CI dependencies for the Zabbix Roles
 ansible==7.0.0
-ansible-compat==0.5.0
+ansible-compat==3.0.0
 ansible-core==2.14.2
-docker==5.0.2
-molecule==3.5.1
-molecule-docker==1.0.2
+docker==6.0.1
+molecule==4.0.4
+molecule-docker==2.1.0
 netaddr==0.8.0
-pytest-testinfra==6.1.0
+pytest==7.2.1
+pytest-testinfra==7.0.0
 ipaddr==2.2.0
 ipaddress==1.0.23
+requests==2.28.2
```

**Comment by pyrodie18** [comment]
@mcbrineellis I'm about to push @BGmot changes to the repo in a few minutes once my current tests run and it should trickle down to you.

**Pull request merged**
