### PR TITLE
1.5.0prep

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Preparation for 1.5.0 release

antsibull-changelog was not run at this moment. waiting for #502

### CODE REVIEW

**Comment by dj-wasabi** [comment]
👍

**Comment by dopice** [comment]
I was looking around a bit but couldn't find any release date for 1.5.0. Do we have one, and is it noted somewhere? Maybe it's just me who need to clean my glasses...

**Review by dj-wasabi — APPROVED** [review]

**Comment by D3DeFi** [comment]
@dopice we once proposed to look at the state of the repo at the start of each month and release if necessary. So far I am failing terribly to do that :)

Anyways, 1.5.0 on its way out now

**Comment by D3DeFi** [comment]
1.5.0 out! should be visible on galaxy within the next 30 minutes:
https://galaxy.ansible.com/community/zabbix

**Comment by dopice** [comment]
> 
> 
> @dopice we once proposed to look at the state of the repo at the start of each month and release if necessary. So far I am failing terribly to do that :)
> 
> Anyways, 1.5.0 on its way out now

Sounds like a good thing to do. Sure, but I still believe you do a great job maintaining! 👍

**Pull request merged**
