### PR TITLE
fixing bug for a empty interfaces list

### PR DESCRIPTION
**Pull request by Mawiguk0**
##### SUMMARY
Fixing the the issue i opened here minutes ago. A simple check for the length of the interfaces list does the job just right.
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
https://github.com/ansible-collections/community.zabbix/blob/main/scripts/inventory/zabbix.py

### CODE REVIEW

**Comment by BGmot** [comment]
Thanks for PR! can you please do proposed little tweak so code looks a bit cleaner?

**Comment by D3DeFi** [comment]
> Thanks for PR! can you please do proposed little tweak so code looks a bit cleaner?

Excuse me if I am wrong, but I don't see anything proposed here.

**Review by D3DeFi — APPROVED** [review]
This is valid PR for me. +1

**Comment by Mawiguk0** [comment]
Just discovered that I need to make a small adjustment. Now the code breaks when providing no interfaces list. I'm pushing a tweak soon

**Comment by Mawiguk0** [comment]
@D3DeFi could you please have a look into my change? I guess this would be a good solution now.

**Review by D3DeFi — APPROVED** [review]
Looks good 🙂

@BGmot Want to add something?

**Comment by BGmot** [comment]
I am confused. Do you see my proposal to replace `>= 1` to `> 0 `?
Please replace or say "we are not doing it", in either case I am good with the PR. Thanks.

**Comment by D3DeFi** [comment]
> I am confused. Do you see my proposal to replace `>= 1` to `> 0 `?
> 
> Please replace or say "we are not doing it", in either case I am good with the PR. Thanks.

I dont see anything like that

**Comment by BGmot** [comment]
image
This is what I see... hmm... maybe I need to learn how to use GitHub -\

**Comment by D3DeFi** [comment]
> image
> 
> This is what I see... hmm... maybe I need to learn how to use GitHub -\

It says pending. You probably clicked 'start a review' instead of 'add single comment' in which cas it waits for you to go to the top right 'review changes' button and select approve/comment/request changes toggles.

**Comment by BGmot** [comment]
do you see it now?

**Comment by D3DeFi** [comment]
> do you see it now?

yep 👍

**Comment by BGmot** [comment]
My sincere apologies, I do need to learn GitHub -(((

**Comment by Mawiguk0** [comment]
So how is this merged now? Does someone of the maintainers need to look into this?

**Review by D3DeFi — APPROVED** [review]
LGTM, will merge after tests pass

**Comment by Mawiguk0** [comment]
do i need to change my branchname? I just added a changelog fragment as mentioned in the contributung guidelines.

**Comment by D3DeFi** [comment]
> do i need to change my branchname? I just added a changelog fragment as mentioned in the contributung guidelines.

no need, everything is fine now. We prefer other branch names instead of main with bigger patches as it allows us to pull PR locally and test it out.

Lets allow tests to finish and then I am merging

**Pull request merged**
