### PR TITLE
Renaming the names of the roles

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

As it provides error while using a dash (-) in the role name, we will use an underscore (_)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

roles zabbix*

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by dj-wasabi** [comment]
@D3DeFi  Can i merge? Or should I wait until you have finished the ci part that roles are excluded during runs?

**Comment by D3DeFi** [comment]
> @D3DeFi Can i merge? Or should I wait until you have finished the ci part that roles are excluded during runs?

merge. Sorry I was away

**Comment by D3DeFi** [comment]
ouchie, integration tests are failing because it uses `roles/zabbix_proxy` instead of `test/integration/targets/zabbix_proxy`.

**Comment by D3DeFi** [comment]
I've pushed fix for sanity tests and will continue searching for workaround on integrations tests tomorrow as it seems to be a bug in `ansible-test` itself. If nothing else works we will simply rename roles in `test/integration/targets` to something like `zabbix_proxy_module`

**Pull request merged**
