### PR TITLE
Fixing path for CentOS/RedHat

### LINKED ISSUE #270: zabbix_web php-fpm does not refer to zabbix.conf
##### SUMMARY

php-fpm does not refer to zabbix.conf created by zabbix_web role

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_web

##### ANSIBLE VERSION
```
2.9.15
```

##### OS / ENVIRONMENT / Zabbix Version
RHEL 7.4 / rh-php72-php-fpm / zabbix_server (Zabbix) 5.0.5 

##### STEPS TO REPRODUCE
```yaml
- name: Install Zabbix Server
  hosts: zabbix_servers
  become: yes
  roles:
    - role: geerlingguy.apache
    - role: community.zabbix.zabbix_web
       zabbix_websrv: apache
       zabbix_php_fpm: True
```

##### EXPECTED RESULTS

php-fpm refers to the generated zabbix.conf
```
/etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
```
##### ACTUAL RESULTS
https://github.com/ansible-collections/community.zabbix/blob/bdc020b19b010704c988b6766f6b33ff66a5aa4c/roles/zabbix_web/tasks/RedHat.yml#L90-L101

php-fpm does not refer to the generated zabbix.conf

```paste below
# Where zabbix.conf is created by role
/etc/opt/rh/rh-php72/zabbix.conf
# Directory referenced by php-fpm. 
/etc/opt/rh/rh-php72/php-fpm.d/*.conf
```

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

* Added Debian to Molecule again;
* Fixing path for CentOS/RedHat;

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

Fixes #270

### CODE REVIEW

**Comment by dj-wasabi** [comment]
@sky-joker @D3DeFi  can you help? First the sanity check failed because `plugins/modules/zabbix_service.py` complained about missing default value, so I added it and now it is failing on multiple tests. I only made changes to the roles, so I am  not sure why the sanity tests are executed even before I had to make changes to `plugins/modules/zabbix_service.py`.

**Comment by D3DeFi** [comment]
@dj-wasabi there seems to be some change in zabbix we may have not seen before. I have created a tracking issue #279 and proposed to disable integration tests #280

If @sky-joker thinks this is a good idea for now, you would need to rebase your PR on top of that #280. Sorry that roles development was interrupted by plugins problem. 

If possible, revert your change to zabbix_service as I have also added it to the #280.

**Comment by dj-wasabi** [comment]
> @dj-wasabi there seems to be some change in zabbix we may have not seen before. I have created a tracking issue #279 and proposed to disable integration tests #280
> 
> If @sky-joker thinks this is a good idea for now, you would need to rebase your PR on top of that #280. Sorry that roles development was interrupted by plugins problem.
> 
> If possible, revert your change to zabbix_service as I have also added it to the #280.

No worries bro! I undid the change. Thanks! :)

**Comment by D3DeFi** [comment]
please rebase on latest main and it should work then

**Review by D3DeFi — APPROVED** [review]

**Pull request merged**
