### PR TITLE
Adding the Zabbix Agent role

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

This PR adds the Zabbix Agent role (version 2.3.0, tagged on 2020-05-05) to be available in the collection. As suggested in a comment on https://github.com/ansible-collections/community.zabbix/issues/16 as is it is now, next step would be moving documentation, testing etc.

##### ISSUE TYPE

- New Role Pull Request

##### COMPONENT NAME

zabbix-agent

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by dj-wasabi** [comment]
@D3DeFi & @sky-joker Some issues are copied to this repository and some were closed. Repository for the Zabbix Agent is now archived.

**Comment by dj-wasabi** [comment]
cc @ericsysmin

**Comment by sky-joker** [comment]
Thank you @dj-wasabi for this PR :)
If @D3DeFi agree, we would like to merge this PR.

**Comment by D3DeFi** [comment]
Absolutely, as discussed previously, lets merge all of the roles and then transform how it looks.

**Comment by D3DeFi** [comment]
> 
> 
> @D3DeFi & @sky-joker Some issues are copied to this repository and some were closed. Repository for the Zabbix Agent is now archived.

I've took a liberty to label them as they were labeled in the original repository.

**Pull request merged**
