### PR TITLE
Allow using other hash methods for postgresql userfor server role (#886)

### PR DESCRIPTION
**Pull request by krauthosting**
##### SUMMARY
See #886

### CODE REVIEW

**Review by BGmot — COMMENTED** [review]
Please add changelog fragment.

**Review by D3DeFi — CHANGES_REQUESTED** [review]
Patch looks good, as @BGmot stated, please add changelog fragment. This is how you do it:
https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

You can also find some fragments already in this repo at changelog/fragments/

**Comment by krauthosting** [comment]
Sorry seems missed to push this yesterday during work, but there you go :+1:

**Review by D3DeFi — APPROVED** [review]
Good from me. Thank you for the contribution! @BGmot ?

Btw does this address #886?

**Review by BGmot — APPROVED** [review]
Looks good too me and yes this addresses #886

**Pull request merged**
