### PR TITLE
Update apache_vhost.conf.j2

### PR DESCRIPTION
**Pull request by amaxcz**
Fixed for version Zabbix 5.0 - values should be added to the /etc/apache2/sites-available/zabbix.conf

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @amaxcz 

Thank you for making time to create a Pull Request. We can not merge an PR when the CI Tests are failing. Can you take a look and investigate what is going and and supply a fix?

If you need help, don't hesitate to ask.

Kind regards,
Werner

**Comment by amaxcz** [comment]
github tasks are broken with 502 Bad Gateway inside :)

**Comment by dj-wasabi** [comment]
Hi @amaxcz 

Sorry for late reply, but I think this PR isn't needed anymore with the recent changes. Can you check and if so, apply fixed as there are some merge conflicts?

**Comment by D3DeFi** [comment]
please reopen if you find this necessary

**Pull request closed without merging**
