### PR TITLE
WIP: Refactor Version dependencies in modules/plugins

### LINKED ISSUE #96: Refactor Version dependencies in modules/plugins
I open this issues in advance to #92 . I would like to do one first small thing and refactor the way modules checks or acts on version dependency. Imo it's a good first and easy thing to contribute - I will open a PR and label it WIP.

##### SUMMARY
For example, from zabbix_host:

```python
self._zbx_api_version = zbx.api_version()[:5]
```

while zabbix_action does it this way:

```python
if float(self._zapi.api_version().rsplit('.', 1)[0]) >= 5.0:
```

Also there one plugin just requests the version everytime or in the `_init` while others pass it through an argument to functions.

##### ISSUE TYPE
- Feature Idea

### PR DESCRIPTION
**Pull request by rockaut**
##### SUMMARY

I would like to do one first small thing and refactor the way modules checks or acts on version dependency. Imo it's a good first and easy thing to contribute.

Will fix #96 and see it for discussion.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
all

### CODE REVIEW

**Comment by D3DeFi** [comment]
@rockaut can you please rebase on top of a recent `master` state? Changes to `zabbix_action` were already applied in #90

**Comment by rockaut** [comment]
Remarks:
- I also used the opportunity to streamline the import parts of the files.
- Rebased it onto master

**Comment by D3DeFi** [comment]
This will be more complicated. Seems more like merge gone wrong.

I would say 52e2f04f9d837083879febfbd8b565cc5f6dd87e needs to get removed completely (those are changes to zabbix_action) and your changes should be shrunk to a single commit preferably without any merge commits. 

Be sure to at least take a backup to not loose any changes in a form of copying this:
https://patch-diff.githubusercontent.com/raw/ansible-collections/community.zabbix/pull/97.patch

Something like this:
- `git reset --soft HEAD`
- revert changes to zabbix_action
- do single commit
- rebase upstream/master
- push -f origin branch

**Comment by rockaut** [comment]
No wait sorry. I realize I just did it wrong - I hate rebase, get it wrong everytime.
Force-pushed it again. I can completelly redo the PR if you wish so ... sorry for screwing it up.

**Comment by sky-joker** [comment]
Sorry, I’ll check this PR in a few days.

**Pull request merged**
