### PR TITLE
Enable Zabbix repo and disable the rest of the repositories

### LINKED ISSUE #242: Disable all not needed repos when using yum to install packages
##### SUMMARY

We have some custom repositories configured on CentOS machines. Those repositories are not avialiable durning everyday use (they are turn on only when the application hosted on those machines is update'ed). I can't remove them so I need to disable them durning update. So far I have found a workaround for this:

In file roles/zabbix_agent/tasks/RedHat.yml I have added this two lines:

```
disablerepo: "*"
enablerepo: "{{ zabbix_repo }}"
```

here:

```
- name: "RedHat | Installing zabbix-agent"
  package:
    pkg:
      - "{{ zabbix_agent_package }}"
    disablerepo: "*"
    enablerepo: "{{ zabbix_repo }}"
    state: "{{ zabbix_agent_package_state }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_agent_package_installed
  until: zabbix_agent_package_installed is succeeded
  become: yes
  tags:
    - init
    - zabbix-agent
```

I have made similar change in task: "RedHat | Installing zabbix-{sender,get}}" (same file)

This worked for me but I'm not sure if this is the only place that needs this change ()
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_agent role

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = /ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_BECOME(/ansible/ansible.cfg) = False
DEFAULT_JINJA2_EXTENSIONS(/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = [u'/ansible/roles']
```

##### STEPS TO REPRODUCE

Do a simple agent install on host with repository from which you cannot download files or is not available.   

```yaml
playbook from example should show this problem
```

##### EXPECTED RESULTS

Install without error

##### ACTUAL RESULTS

```paste below
FAILED - RETRYING: RedHat | Installing zabbix-agent (2 retries left).Result was: {
    "attempts": 2,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "zabbix-agent"
            ],
            "pkg": [
                "zabbix-agent"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: CustomRepoName. Please verify its path and try again",
    "retries": 4
}
```

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Fixes #242 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Role: all
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by D3DeFi** [comment]
Just a theoretical question as I don't see this step then being reverted back after installation. Wouldn't this leave production systems in a state where only zabbix repo is enabled?

Administrators would probably want more than just zabbix repo enabled.

**Comment by dj-wasabi** [comment]
> Just a theoretical question as I don't see this step then being reverted back after installation. Wouldn't this leave production systems in a state where only zabbix repo is enabled?
> 
> Administrators would probably want more than just zabbix repo enabled.

We don't disable/enable anything on the host with this, we only "configure" the `yum install` command to use 1 (or basically 2) yum repositories to look for the packages instead of all repositories that are configured on the host. If for example you have 10 different yum repositores configured on your host and 4 of them contains the Zabbix packages, based on the priority (and maybe luck) you are able to install them from the official Zabbix yum repository and not from the other 3.

But I think this needs to be configurable, so I will probably change this PR to a WIP so I won't bother you with spam.. 😄

**Comment by D3DeFi** [comment]
> > Just a theoretical question as I don't see this step then being reverted back after installation. Wouldn't this leave production systems in a state where only zabbix repo is enabled?
> 
> > 
> 
> > Administrators would probably want more than just zabbix repo enabled.
> 
> 
> 
> We don't disable/enable anything on the host with this, we only "configure" the `yum install` command to use 1 (or basically 2) yum repositories to look for the packages instead of all repositories that are configured on the host. If for example you have 10 different yum repositores configured on your host and 4 of them contains the Zabbix packages, based on the priority (and maybe luck) you are able to install them from the official Zabbix yum repository and not from the other 3.
> 
> 
> 
> But I think this needs to be configurable, so I will probably change this PR to a WIP so I won't bother you with spam.. 😄 

Makes sense then. Thanks for explanation. I haven't had time to really dwelve into the documentation. That is why it was just a theoretical question! 😁

**Comment by dj-wasabi** [comment]
> > > Just a theoretical question as I don't see this step then being reverted back after installation. Wouldn't this leave production systems in a state where only zabbix repo is enabled?
> > 
> > 
> > > 
> > 
> > 
> > > Administrators would probably want more than just zabbix repo enabled.
> > 
> > 
> > We don't disable/enable anything on the host with this, we only "configure" the `yum install` command to use 1 (or basically 2) yum repositories to look for the packages instead of all repositories that are configured on the host. If for example you have 10 different yum repositores configured on your host and 4 of them contains the Zabbix packages, based on the priority (and maybe luck) you are able to install them from the official Zabbix yum repository and not from the other 3.
> > But I think this needs to be configurable, so I will probably change this PR to a WIP so I won't bother you with spam.. 😄
> 
> Makes sense then. Thanks for explanation. I haven't had time to really dwelve into the documentation. That is why it was just a theoretical question! 😁

No worries bro! 👍

**Pull request merged**
