### PR TITLE
Split the way to enable support for software collection (CentOS and RHEL)

### LINKED ISSUE #202: Role cannot install Zabbix web 5.0 on RHEL 7
##### SUMMARY
Despite using the name "RedHat", the zabbix_web role can only install on CentOS, not RHEL 7 (EL 8 is another story).
This is due to the reliance on the [CentOS SCL](https://github.com/ansible-collections/community.zabbix/blob/1.0.0/roles/zabbix_web/tasks/RedHat.yml#L50) which in RHEL doesn't exist.
The CentOS SCL project documents the alternative for [RHEL on their GitHub](https://github.com/sclorg/centos-release-scl#how-to-install-sclo-packages-on-rhel-systems).

Also, note that the [documented default](https://github.com/ansible-collections/community.zabbix/blob/f1f4b9db36554f825c4d4e26cd6101478d28411f/docs/ZABBIX_WEB_ROLE.md#overall-zabbix) and [actual default value](https://github.com/ansible-collections/community.zabbix/blob/1.0.0/roles/zabbix_web/defaults/main.yml#L8) do not match for the parameter * zabbix_web_centos_release*.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix_web

##### ANSIBLE VERSION
```paste below
ansible 2.9.9
```

##### CONFIGURATION
```paste below
DISPLAY_SKIPPED_HOSTS(/Users/bmt/git/ansible-zabbix/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Red Hat Enterprise Linux 7

##### STEPS TO REPRODUCE
Try to deploy zabbix_web on RHEL 7.

##### EXPECTED RESULTS
The role should set the right Yum repo on RHEL 7 to install the web and PHP rpm needed by Zabbix 5.0.

##### ACTUAL RESULTS
```paste below
FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'centos-release-scl' found available, installed or updated", "rc": 126, "results": ["No package matching 'centos-release-scl' found available, installed or updated"]}
```

### PR DESCRIPTION
**Pull request by senyoltw**
##### SUMMARY
Split the way to enable support for software collection (CentOS and RHEL)

Fixes #202

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_web

##### ADDITIONAL INFORMATION
Tested on RHEL 7.4
Reference Documents
- https://www.softwarecollections.org/en/docs/guide/#sect-Enabling_Support_for_Software_Collections
- https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/packaging_guide/sect-enabling_support_for_software_collections

### CODE REVIEW

**Comment by senyoltw** [comment]
Some tests fail because `set-env` command disabled. Suggested fix in pull request 265.

**Comment by dj-wasabi** [comment]
> Some tests fail because `set-env` command disabled. Suggested fix in pull request 265.

Hi, thank you for this comment. The mentioned PR is merged.

**Comment by senyoltw** [comment]
Thanks for the pull request 265 merge. But, I don't know how to re-running Github actions. 
Can you re-running Github actions? or should I wait for a fix in the review?
To be sure, In my forked repository I'm sure the test will pass https://github.com/senyoltw/community.zabbix/actions/runs/376147414

**Comment by dj-wasabi** [comment]
@senyoltw What you can do it a `git pull origin main` in the branch you are working on and push that. With the git pull command you donwload the most recent changes into your branch and when you push that again, it will trigger the jobs. Otherwise if we manually execute the actions then we are rebuilding the current branch which goes into error.

**Comment by dj-wasabi** [comment]
Thanks! 👍

**Pull request merged**
