### PR TITLE
fix zabbix_action module for zabbix6

### LINKED ISSUE #600: zabbix_action returns Invalid parameter
I'm trying to add a zabbix_action using the following:

```
- name: Deploy trigger action
  zabbix_action:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_web_user }}"
    login_password: "{{ zabbix_web_password }}"
    name: "Send alerts to the OPS team"
    event_source: 'trigger'
    state: present
    status: enabled
    esc_period: 1h
    conditions:
      - type: host_group
        operator: 'like'
        value: 'Zabbix servers'
    operations:
      - type: send_message
        media_type: 'Slackv2'
        send_to_users:
          - 'Admin'
    acknowledge_operations:
      - type: send_message
        media_type: 'Slackv2'
        send_to_users:
          - 'Admin'
    recovery_operations:
      - type: send_message
        media_type: 'Slackv2'
        send_to_users:
          - 'Admin'
```

The media type `Slackv2` already exists. The error that I get is:

```
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2238 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/lucas/.ansible/cp/9533ba4d4c localhost '/bin/sh -c '"'"'rm -f -r /home/lucas/.ansible/tmp/ansible-tmp-1641272906.19573-89276-206089095450568/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_********_action_payload_0ewax9qz/ansible_********_action_payload.zip/ansible_collections/community/********/plugins/modules/********_action.py", line 917, in add_action
  File "/usr/local/lib/python3.8/dist-packages/********_api.py", line 341, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/local/lib/python3.8/dist-packages/********_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/local/lib/python3.8/dist-packages/********_api.py", line 348, in do_request
    return self.parent.do_request(req)
  File "/usr/local/lib/python3.8/dist-packages/********_api.py", line 299, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
fatal: [zabbixsecondary1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "acknowledge_default_message": "",
            "acknowledge_default_subject": "",
            "acknowledge_operations": [
                {
                    "command": null,
                    "command_type": null,
                    "execute_on": null,
                    "media_type": "Slackv2",
                    "message": null,
                    "password": null,
                    "port": null,
                    "run_on_groups": null,
                    "run_on_hosts": null,
                    "script_name": null,
                    "send_to_groups": null,
                    "send_to_users": [
                        "Admin"
                    ],
                    "ssh_auth_type": null,
                    "ssh_privatekey_file": null,
                    "ssh_publickey_file": null,
                    "subject": null,
                    "type": "send_message",
                    "username": null
                }
            ],
            "conditions": [
                {
                    "formulaid": null,
                    "operator": "like",
                    "type": "host_group",
                    "value": "Zabbix servers",
                    "value2": null
                }
            ],
            "default_message": "",
            "default_subject": "",
            "esc_period": "1h",
            "eval_type": null,
            "event_source": "trigger",
            "formula": null,
            "http_login_password": null,
            "http_login_user": null,
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "name": "Send alerts to the OPS team",
            "operations": [
                {
                    "command": null,
                    "command_type": null,
                    "esc_period": null,
                    "esc_step_from": 1,
                    "esc_step_to": 1,
                    "execute_on": null,
                    "host_groups": null,
                    "inventory": null,
                    "media_type": "Slackv2",
                    "message": null,
                    "operation_condition": null,
                    "password": null,
                    "port": null,
                    "run_on_groups": null,
                    "run_on_hosts": null,
                    "script_name": null,
                    "send_to_groups": null,
                    "send_to_users": [
                        "Admin"
                    ],
                    "ssh_auth_type": null,
                    "ssh_privatekey_file": null,
                    "ssh_publickey_file": null,
                    "subject": null,
                    "templates": null,
                    "type": "send_message",
                    "username": null
                }
            ],
            "pause_in_maintenance": true,
            "recovery_default_message": "",
            "recovery_default_subject": "",
            "recovery_operations": [
                {
                    "command": null,
                    "command_type": null,
                    "execute_on": null,
                    "media_type": "Slackv2",
                    "message": null,
                    "password": null,
                    "port": null,
                    "run_on_groups": null,
                    "run_on_hosts": null,
                    "script_name": null,
                    "send_to_groups": null,
                    "send_to_users": [
                        "Admin"
                    ],
                    "ssh_auth_type": null,
                    "ssh_privatekey_file": null,
                    "ssh_publickey_file": null,
                    "subject": null,
                    "type": "send_message",
                    "username": null
                }
            ],
            "server_url": "http://********-primary.prod.example.com",
            "state": "present",
            "status": "enabled",
            "timeout": 10,
            "validate_certs": true
        }
    },
    "msg": "Failed to create action 'Send alerts to the OPS team': ('Error -32602: Invalid params., Invalid parameter \"/1\": unexpected parameter \"acknowledge_operations\". while sending {\"jsonrpc\": \"2.0\", \"method\": \"action.create\", \"params\": {\"name\": \"Send alerts to the OPS team\", \"eventsource\": \"0\", \"esc_period\": \"1h\", \"filter\": {\"conditions\": [{\"conditiontype\": \"0\", \"value\": \"4\", \"operator\": \"2\"}], \"evaltype\": \"0\"}, \"operations\": [{\"operationtype\": \"0\", \"esc_step_from\": 1, \"esc_step_to\": 1, \"opmessage\": {\"default_msg\": \"1\", \"mediatypeid\": \"35\"}, \"opmessage_usr\": [{\"userid\": \"1\"}], \"opconditions\": []}], \"recovery_operations\": [{\"operationtype\": \"0\", \"opmessage\": {\"default_msg\": \"1\", \"mediatypeid\": \"35\"}, \"opmessage_usr\": [{\"userid\": \"1\"}]}], \"acknowledge_operations\": [{\"operationtype\": \"0\", \"opmessage\": {\"default_msg\": \"1\", \"mediatypeid\": \"35\"}, \"opmessage_usr\": [{\"userid\": \"1\"}]}], \"status\": \"0\", \"pause_suppressed\": \"1\"}, \"auth\": \"a7b532f59898902ea21066dc9759151a\", \"id\": 3}', -32602)"
}
```

Ansible version:

```
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/lucas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/lucas/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.9 (main, Nov 21 2021, 03:16:13) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 2.11.3
  libyaml = False
```

Zabbix version: `6.0.0beta1`

Not sure if this is a bug or if I'm missing something?

### PR DESCRIPTION
**Pull request by crashwind**
##### SUMMARY
- add zabbix 6.0 api support for zabbix_action module

Fixes #600 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_action

##### ADDITIONAL INFORMATION
'unexpected parameter "acknowledge_operations"' error

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]

**Comment by D3DeFi** [comment]
changes are ok for me, sanity is failing unfortunately due to upstream changes in ansible-test binary, but doesn't relate to your PR at all.

thank you for this patch. Good job! :)

**Comment by D3DeFi** [comment]
@crashwind can you please rebase your PR on top of latest `main`? sanity tests should be now fixed

**Comment by crashwind** [comment]
> 

done. thank you

**Review by D3DeFi — APPROVED** [review]

**Comment by D3DeFi** [comment]
Thank you for the fix! :)

**Pull request merged**
