### PR TITLE
Add Modules for items, triggers, discoveryrules, item prototypes, and trigger prototypes to project

### PR DESCRIPTION
**Pull request by aplathrop**
##### SUMMARY
Added modules for items, triggers, discovery rules, item prototypes, and trigger prototypes that leverages the item, trigger, discovery rule, itemprototype, and triggerprototype API methods (get, create, update, delete)

Note the discovery rules that this PR implements are the LLD rules, not the network discovery rules (which are already implemented)

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- zabbix_item
- zabbix_trigger
- zabbix_discoveryrule
- zabbix_itemprototype
- zabbix_triggerprototype

##### ADDITIONAL INFORMATION

I wanted to be able to add items and triggers, along with their prototype counterparts to hosts using the API, but the modules did not exist, so I created them. They also can be added to templates rather than hosts.

### CODE REVIEW

**Comment by pyrodie18** [comment]
Please check your linting but other than that, it looks good.

**Comment by aplathrop** [comment]
@pyrodie18 Thanks. I think I fixed the issues the linting found, can you give the workflow another run when you get a chance?

**Comment by pyrodie18** [comment]
Great work and thank you for the addition.

**Comment by aplathrop** [comment]
@pyrodie18 No problem, thanks for merging

**Pull request merged**
